### ISSUE TITLE
DeserializeAsync does not update Stream position when TryGetBuffer returns false

### ISSUE THREAD

**Issue by DavidZidar** [Cysharp/MemoryPack#100]
`DeserializeAsync` does not update Stream position when deserializing an object from a Stream in the case that `TryGetBuffer` returns false. This isn't an issue when deserializing a single object from a Stream but not ideal when trying to deserialize several.

From what I can tell it looks like `DeserializeAsync` does a `ms.Seek(bytesRead, SeekOrigin.Current)` when it's working with the buffer but this has been left out in the more complicated case where the buffer can't be used.

Here is a sample program that demonstrates the issue:
```cs
using MemoryPack;

using var ms = new MemoryStream();
await MemoryPackSerializer.SerializeAsync(ms, new Item());
await MemoryPackSerializer.SerializeAsync(ms, new Item());

ms.Seek(0, SeekOrigin.Begin);

// Multiple generic DeserializeAsync works with MemoryStream that can return a buffer as Stream position is correctly updated
await MemoryPackSerializer.DeserializeAsync<Item>(ms);
await MemoryPackSerializer.DeserializeAsync<Item>(ms);

ms.Seek(0, SeekOrigin.Begin);

// Multiple non-generic DeserializeAsync also works with MemoryStream that can return a buffer as Stream position is correctly updated
await MemoryPackSerializer.DeserializeAsync(typeof(Item), ms);
await MemoryPackSerializer.DeserializeAsync(typeof(Item), ms);

// TryGetBuffer will return false with this MemoryStream
using var ms2 = new MemoryStream(ms.ToArray());

// Multiple generic DeserializeAsync does not work with MemoryStream that don't return a buffer as position is not updated
await MemoryPackSerializer.DeserializeAsync<Item>(ms2);
await MemoryPackSerializer.DeserializeAsync<Item>(ms2); // throws, Stream is already at the end

ms2.Seek(0, SeekOrigin.Begin);

// Multiple non-generic DeserializeAsync does not work with MemoryStream that don't return a buffer as position is not updated
await MemoryPackSerializer.DeserializeAsync(typeof(Item), ms2);
await MemoryPackSerializer.DeserializeAsync(typeof(Item), ms2); // throws, Stream is already at the end

[MemoryPackable]
public partial record Item
{
	public string Value { get; init; } = Guid.NewGuid().ToString();
}
```

**Comment by neuecc** [comment]
Stream is not suitable for reading continuous data connected by Stream because it reads everything into a temporary Buffer.

**Comment by DavidZidar** [comment]
I use RecyclableMemoryStream to avoid large heap allocations. Since I can't know beforehand how many bytes to read I'd have to read everything into a temporary buffer myself to get around the bug and use a different overload but then I have the same issue anyway.

**Comment by neuecc** [comment]
In a typical pattern, it is sufficient to write in length-prefix framing.
Also, if you can have your own temporary buffer, there is an overload called `int Deserialize<T>(ReadOnlySpan/ReadOnlySequence, ref T)`.
If you accept a value in ref, the return value will be the consumed length.

**Comment by DavidZidar** [comment]
Streams have one big advantage though and that is that they are a common abstraction, it doesn't matter if I read from memory, a file, a really large file, or a network connection. Other serializers support these use cases, including MessagePack.

I'd argue that this should be supported but I understand that if you read everything into a buffer then that would only work for memory streams and seekable files anyway.

**Comment by neuecc** [comment]
In the case of MessagePack, the format itself can measure the length of the payload to some extent, but not MemoryPack.
And it is undesirable to treat a reading as unread once it has been read, because it is misleading in terms of performance.

**Comment by DavidZidar** [comment]
I see, that makes sense. I suppose I could create my own abstraction that writes the length first and then reads each part into its own RecyclableMemoryStream, that would work for me.

Thanks for your responses. Do you want me to close this issue or leave it open?

**Comment by neuecc** [comment]
Thanks, I will close.

Version Tolerant may be handled well since the length is listed in the header.
I will think about it.

**Comment by neuecc** [comment]
One more thing, Deserialize supports ReadOnlySeqeunce by System.IO.Pipelines, so it is better to use Pipelines instead of Stream.
RecyclableMemoryStream is an old technique, not for use in modern high-performance code.

**Comment by DavidZidar** [comment]
Thanks, I'll keep that in mind. I did get my length prefix workaround to work so I'll use that for now.
