### ISSUE TITLE
Performance downgrade in dotnet 7

### ISSUE THREAD

**Issue by Wyzzcow** [Cysharp/MemoryPack#102]
Hi!
I was running some benchmarks using dotnetbenchmark and noticed a small performance drop using dotnet 7.
The benchmark uses the sample class provided in the readme and simply does the following

```
[MemoryDiagnoser]
public class BenchmarkMemoryPack
{
    private Sample s = new();

    [Benchmark]
    public void MemoryPack()
    {
        MemoryPackSerializer.Deserialize<Sample>(MemoryPackSerializer.Serialize(s));
    }
}
```
Here are the results
```
dotnet 7

|                   Method |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|------------------------- |---------:|--------:|--------:|-------:|----------:|
| MemoryPack               | 147.1 ns | 3.18 ns | 8.97 ns | 0.0296 |     128 B |

dotnet 6

|                   Method |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|------------------------- |---------:|--------:|--------:|-------:|----------:|
| MemoryPack               | 123.1 ns | 3.25 ns | 8.90 ns | 0.0296 |     128 B |

```
Since the readme mentions to use dotnet 7 for best performance, I thought it was worth bringing up.

**Comment by neuecc** [comment]
thanks, I've confirmed.

**Comment by neuecc** [comment]
I've fixed some code and get improved result.

![image](https://user-images.githubusercontent.com/46207/207657554-b5294685-15dc-40e9-9e6d-1eb94072d0b5.png)

However, even now, NET 7 tends to be slower than NET 6 for plain classes.
For nested classes, NET 7 should give better results.
Improvement in the case of plain classes is an issue for the future.
