### ISSUE TITLE
Use [MemoryPackOrder] attribute on auto-generated properties via [ObservableProperty]?

### ISSUE THREAD

**Issue by NickThissen** [Cysharp/MemoryPack#108]
I would like to use MemoryPack to serialize some objects with circular references. It seems like this requires me to add `[MemoryPackOrder]` attributes to each property, right?

Unfortunately my classes are using the MVVM Community Toolkit source generators to auto-generate properties from fields. Instead of a full property I only defined the field with a `[ObservableProperty]` attribute, and the property is generated.
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty

This means I cannot put the `[MemoryPackOrder]` attribute, because the property isn't there in my code. The `[ObservableProperty]` also doesn't seem to support 'forwarding' other attributes (except for a few specific validation cases), so this does not work either:

```csharp
    [MemoryPackable(GenerateType.CircularReference)]
    public partial class Person : ObservableObject
    {
        public Person()
        {
            Friends = new List<Person>();
        }

        [MemoryPackOrder(0)]
        [ObservableProperty]
        private int _id;

        [MemoryPackOrder(1)]
        [ObservableProperty]
        private string _name;

        [MemoryPackOrder(2)]
        public List<Person> Friends { get; }
    }
```
Id and Name properties are generated, but not serialized.

Apart from getting rid of `[ObservableProperty]` and going back to manual properties, is there anything MemoryPack can do to help here? Maybe the source generator can look for the `[ObservableProperty]` attributes and generate serialization for the property instead?

**Comment by neuecc** [comment]
I think this should request to MVVM Community Toolkit.
For example, ObservablePropertyAttribute support attribute,
`[ObservableProperty, typeof(MemoryPackOrder), 0]`

**Comment by NickThissen** [comment]
Actually, I found out that there is a preview version that supports something like that:
https://devblogs.microsoft.com/dotnet/announcing-dotnet-community-toolkit-v810-preview-1/#custom-attributes-for-observableproperty-%f0%9f%a4%96

I can use the following to make sure the generated property includes the MemoryPackOrder attribute:
```
        [ObservableProperty]
        [property: MemoryPackOrder(0)]
        private int _id;
```

Indeed it generates something like this:
```
[MemoryPackOrder(0)]
public int Id {get; set;}
```

Unfortunately, this isn't helpful. I guess because your serialization source generator cannot look at the result of the MVVM toolkit source generator, but only at the actual source. Right? Even though the property is being generated, your serialization isn't picking up on it because it doesn't exist yet in the actual source code.

I think the only way to make it work is to make MemoryPack somehow aware of this attribute.

**Comment by neuecc** [comment]
Okay, it seems that each Source Generator is independent and there is no way to chain them.
However, we still can't provide special support here.
This seems to affect the Json Source Generator as well, and I wonder if you could make a request to the MVVM Community Toolkit?

It would be nice if partial property was implemented, since the approach of generating property from field is bad to begin with.

**Comment by neuecc** [comment]
I see, so that's fine, since the added properties via ObserverProperty are not included.
I think it's a perfect solution.
