### ISSUE TITLE
Why is [MemoryPackOrder] required?

### ISSUE THREAD

**Issue by NickThissen** [Cysharp/MemoryPack#112]
I need to serialize with CircularReference option enabled. Now MemoryPack requires me to add `[MemoryPackOrder]` to all properties. I'm just wondering why this is necessary, and if there could be an option to omit these attributes?

The only reason I can think of is for version compatibility (so you can deserialize data that was serialized with a different "version" of the model, with different properties). In my case, this is not an issue as the serialization and deserialization will always be "in sync" with the same model. Could it be possible to add an opt-in to omit the order attributes, with the "risk" that deserialization will fail if the version was not in sync?

Alternatively, would it be possible to set the order in code via reflection, just like you can use the `DynamicUnionFormatter` for base classes to avoid Union attribute everywhere? For example - on initialize I can probably get a list of properties that have to be serialized, and then I can just register them all with an incrementing order number. When I add or remove properties later, the order will be different the next runtime, but I don't care because I guarantee that both sides are in sync anyway.

Not a big deal, just would be a nice addition for large models with many properties already defined. It's a chore to add all the orders and even bigger chore to later add more properties; it's easy to lose track of which numbers are already in use...

**Comment by neuecc** [comment]
Ok, previously VersionTolerant/CircularReference automatically set as StructLayout.Explicit.
`v1.9.11` supports explicit `SerializeLayout.Sequential`.

```csharp
[MemoryPackable(GenerateType.CircularReference, SerializeLayout.Sequential)]
public partial class Foo
```
