### ISSUE TITLE
MemoryPackFormatter for struct.

### ISSUE THREAD

**Issue by juliolitwin** [Cysharp/MemoryPack#113]
MemoryPackFormatter not working for structs? I tested it with class and it worked, so with struct the formatter is not called.
Cheers.

**Comment by neuecc** [comment]
Please submit the code.
If you are talking about creating your own Formatter but it is not called, the formatter will not be called if it is an unamanged struct.

**Comment by juliolitwin** [comment]
Oops @neuecc, I ended up putting it off to submit the sample code and forgot about it.

I need to treat some specifics structs to be able to use packed values in my own way. Using .net 6.

**Struct**:

```csharp
[MemoryPackable]
public partial struct ObjectGuid : IEquatable<ObjectGuid>
{
    public ulong Low { get; set; }
    public ulong High { get; set; }

    public ObjectGuid(ulong high, ulong low)
    {
        Low = low;
        High = high;
    }

    public static bool operator ==(ObjectGuid first, ObjectGuid other) => first != null && other != null && first.Equals(other);
    public static bool operator !=(ObjectGuid first, ObjectGuid other) => !(first == other);
    public override bool Equals(object obj) => obj != null && obj is ObjectGuid && Equals((ObjectGuid)obj);
    public bool Equals(ObjectGuid other) => other != null && other.High == High && other.Low == Low;
    public override int GetHashCode() => new { High, Low }.GetHashCode();
    public bool IsEmpty() => Low == 0 && High == 0;
}
```

**Formatter**:
PS: I added a 'for' to add the bytes, as there isn't a function where I can pass the byte[] and in it pass the size that is to be serialized.

```csharp

public class ObjectGuidFormatter : MemoryPackFormatter<ObjectGuid>
{
    public override void Deserialize(ref MemoryPackReader reader, ref ObjectGuid value)
    {
        var loLength = reader.ReadValue<byte>();
        var hiLength = reader.ReadValue<byte>();
        var low = ReadPackedUInt64(ref reader, loLength);

        value = new ObjectGuid(ReadPackedUInt64(ref reader, hiLength), low);
    }

    public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref ObjectGuid value)
    {
        var loSize = PackUInt64(value.Low, out var lowMask, out var lowPacked);
        var hiSize = PackUInt64(value.High, out var highMask, out var highPacked);

        writer.WriteValue(lowMask);
        writer.WriteValue(highMask);

        for (var i = 0; i < loSize; i++)
        {
            writer.WriteValue(lowPacked[i]);
        }

        for (var i = 0; i < hiSize; i++)
        {
            writer.WriteValue(highPacked[i]);
        }
    }

    private uint PackUInt64(ulong value, out byte mask, out byte[] result)
    {
        uint resultSize = 0;
        mask = 0;
        result = new byte[8]; // pool

        for (byte i = 0; value != 0; ++i)
        {
            if ((value & 0xFF) != 0)
            {
                mask |= (byte)(1 << i);
                result[resultSize++] = (byte)(value & 0xFF);
            }

            value >>= 8;
        }

        return resultSize;
    }

    private ulong ReadPackedUInt64(ref MemoryPackReader reader, byte length)
    {
        if (length == 0) return 0;

        var guid = 0ul;

        for (var i = 0; i < 8; i++)
            if ((1 << i & length) != 0)
                guid |= (ulong)reader.ReadValue<byte>() << (i * 8);

        return guid;
    }
}
```

**Testing**:

```csharp
[MemoryPackable]
public partial class TestData
{
    public ObjectGuid Guid;
    public string Name;
}

static void Main()
{
    var objectGuid = new ObjectGuid(1231231231, 1);

    MemoryPackFormatterProvider.Register<ObjectGuid>(new ObjectGuidFormatter());

    var bin = MemoryPackSerializer.Serialize(new TestData
    {
        Name = "Test",
        Guid = objectGuid,
    });

    var obj = MemoryPackSerializer.Deserialize<TestData>(bin);
}
```

**Comment by neuecc** [comment]
Ok, struct(ulong, ulong) is unmanaged struct(doesn't contain reference types).
For performance reasons, the serialization behavior cannot be changed.

If you want to change it, you can add a dummy reference type.

```csharp
object _dummy;
````

Additional memory consumption may also be unnecessary if StructLayout is adjusted.

**Comment by juliolitwin** [comment]
Thanks, it really worked with the `object _dummy`. And yes, I'm worried about memory allocation because with dummy, the size increased by 6. I tried to make some adjustments with StructLayout, but it still remains with the size of the object.

Regarding Vector2/Vector3 there is nothing I can do then, correct? Will I have to create a new Vector2/Vector3 struct to serialize to use in a packed way?

**Comment by neuecc** [comment]
Oh, can't overlap the reference type and struct, sorry.
Yes, there is a need to create custom non-unamanged types for Vector2 and others as well.

BTW, if size is an issue, why not target Guid[] or Vector2[] instead of compacting Guid or Vector2?
That would be customizable and could be made much smaller by various compression methods.
In addition to applying it to the whole, you can also use Attribute to apply it to a specific field (built-in, e.g., [BrotliFormatter]).
