### ISSUE TITLE
序列化方法能不能返回已经写入长度

### ISSUE THREAD

**Issue by wj8400684** [Cysharp/MemoryPack#117]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/39239954/216767175-c501eba3-91db-4553-894f-adec2be50498.png">

**Comment by neuecc** [comment]
use MemoryPackWriter overload instead.

```csharp
using (var state = MemoryPackWriterOptionalStatePool.Rent(options))
{
    var writer= new MemoryPackWriter<>(ref bufWriter, state);
    MemoryPackSerializer.Serialize(ref writer, value);
    // writer.WrittenCount
}
```

**Comment by wj8400684** [comment]
Thank!

**Comment by wj8400684** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/39239954/216908976-9e99f4ff-7475-444b-9a0c-408ffe0c5a2f.png">
Which of the two methods is faster?

**Comment by wj8400684** [comment]
![image](https://user-images.githubusercontent.com/39239954/216914106-a39ca424-9ec9-4466-b288-ce68358aff3f.png)
It doesn't seem to work！

**Comment by wj8400684** [comment]
Thank!
