### ISSUE TITLE
Support streaming for Unity

### ISSUE THREAD

**Issue by MikMog** [Cysharp/MemoryPack#125]
Hey, I was wondering if somehow the streaming examples from the documentation could work in Unity? What would it take to support this?

**Comment by neuecc** [comment]
dependency: `System.IO.Pipelines`

**Comment by MikMog** [comment]
I added System.IO.Pipelines, but the Unity release doesn't have MemoryPack.Streaming included. When including it manually, I get some errors, since it is using some code overrides that are not present.

**Comment by MikMog** [comment]
Yes, it was the generic definition it complained about, but perhaps there is a quick fix I can work out.
