### ISSUE TITLE
Can BrotliCompressor/BrotliDecompressor be used with async?

### ISSUE THREAD

**Issue by chmodseven** [Cysharp/MemoryPack#127]
I would like to be able to use this async variation of the BrotliCompressor:

            await using (BrotliCompressor compressor = new BrotliCompressor (CompressionLevel.Fastest))
            {
                await MemoryPackSerializer.SerializeAsync (compressor, data);
                return compressor.ToArray ();
            }

However, the SerializeAsync only seems to take a Stream and not the compressor, unless I'm missing something obvious.  Also the BrotliCompressor itself doesn't have IDisposable and so it doesn't like the first await either, which would also be nice to have present.  For synchronous, by comparison, this similar piece of code works fine:

            using (BrotliCompressor compressor = new BrotliCompressor (CompressionLevel.Fastest))
            {
                MemoryPackSerializer.Serialize (compressor, data);
                return compressor.ToArray ();
            }

I have managed to get the async to work by changing to BrotliStream instead, however I am then finding that there are some discrepancies in the final few bytes of the two byte arrays when comparing between sync with BrotliCompressor and async with BrotliStream, so it seems like the two are not 100% comparable or there is a bug somewhere, or perhaps I am missing a flush in there somewhere or something.

**Comment by neuecc** [comment]
BrotliCompressor/Decompressor works only on in-memory buffers.
Serialize does not need to be asynchronous.
However, adds `BrotliCompressor.CopyToAsync(Stream)` will be ok.

**Comment by neuecc** [comment]
However, we would like it to be used in conjunction with PipeWriter/Reader (System.IO.Pipelines), as shown in the Document.
