### ISSUE TITLE
Dynamic deserialize based on keys

### ISSUE THREAD

**Issue by juhani-honkala** [Cysharp/MemoryPack#128]
Hello, thank you for providing this library. I'm interested in utilizing it for efficient serialization.

In certain scenarios, it can be cumbersome to copy TypeScript-generated classes. Is it feasible to implement a deserialization function that utilizes optional property keys to automatically deserialize objects based on incoming data? This would provide greater flexibility, and for larger sturctures, the object structure could be sent only once, e.g. for an array of 1000 items.

**Comment by neuecc** [comment]
In C# only, CircularReference holds the ID.
In TypeScript, there are currently no plans to include such a complex implementation.
