### ISSUE TITLE
Requirement to be protected for [MemoryPackInclude] private members of parent classes

### ISSUE THREAD

**Issue by frolushka** [Cysharp/MemoryPack#129]
I found really non-obvious behavior for me. Here a synthetic code example:
```
[MemoryPackable(SerializeLayout.Explicit)]
[MemoryPackUnion(0, typeof(TestChild))]
public abstract partial class TestParent
{
	[MemoryPackOrder(0)]
	public int A;

	[MemoryPackOrder(1)]
	private int B;
		
	[MemoryPackOrder(2)]
	public int C;
}

[MemoryPackable(SerializeLayout.Explicit)]
public sealed partial class TestChild : TestParent
{
	[MemoryPackOrder(3)]
	public int D;
}
```
It throws an compile error `MEMPACK026: The MemoryPackable object 'TestChild' member 'C' is not continuous number from zero`.

I found that `private` fields must be marked with `MemoryPackInclude` even if they already marked with `MemoryPackOrder`. It's OK.
However, there is one more, more hidden requirement. Considering that the codegen works with classes defined in `MemoryPackUnion`, it will not access private fields of his parent, so I can't use `private` for any parent `MemoryMarkable` classes. With `protected` access modifier example compiles fine.

Could you add this requirement (use protected access modifier, not private) to the documentation? I think it will save some time for searchers like me. :)

**Comment by neuecc** [comment]
Thank you, I see, I had omitted to consider the relationship between MemoryPackOrder and private.

I've added new diagnostics `MEMPACK036 Inherit type can not include private member`.
It will release soon.
