### ISSUE TITLE
Codegen silently skip readonly class members

### ISSUE THREAD

**Issue by frolushka** [Cysharp/MemoryPack#130]
Here is simple correctly compiling code:
```
[MemoryPackable]
public partial class Test
{
	public readonly int A;
}
```

However, there is no A field in generated Deserialize method:
```
SET:
        

        goto READ_END;

    NEW:
        value = new Test()
        {

        };
```

Could you add a check does class with readonly MemoryPackable members has MemoryPackableConstructor? Or may be add remark to documentation that readonly fields serialized ONLY if containing class has a MemoryPackableConstructor?

**Comment by neuecc** [comment]
Thanks, I've add `MEMPACK037 Readonly field must be constructor member`
