### ISSUE TITLE
How can "Serialization Info" be used in Unity?

### ISSUE THREAD

**Issue by euglenach** [Cysharp/MemoryPack#133]
MemoryPack has a nice feature called "Serialisation Info".
https://github.com/Cysharp/MemoryPack#serialization-info

This feature requires editing the .csproj file. The Unity editor automatically generates the .csproj file, so editing is disabled.
A different approach should be needed.
The .unitypackage in the release contains "MemoryPack.Generator.Roslyn3.dll" and seems to check for the presence of the "MemoryPackGenerator_SerializationInfoOutputDirectory" option in the "MemoryPackGenerator.Execute method".
So I think it is possible to use "Serialisation Info" in the current environment, but it would be great if you could also include in the documentation how to set it up for Unity.
Or is it possible to tell us how to do that here?

Thank you.

**Comment by neuecc** [comment]
Perhaps it is not currently possible to pass values this way in Unity.
I'm thinking that a JSON-like approach with AdditionalText would be more solid (and probably work with Unity), 
but in any case, It can't do right now.
