### ISSUE TITLE
Type System.Lazy`1 is not found in compilation.

### ISSUE THREAD

**Issue by frolushka** [Cysharp/MemoryPack#134]
I got the following error in generator on Windows (on OS X everything is fine):
```
warning CS8785: Generator 'MemoryPackGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Type System.Lazy`1 is not found in compilation.'
```
The problem place is `Compilation.GetTypeByMetadata` method invoke. I'm not sure, but I'm guessing `Lazy` is defined in `mscorlib` and `nunit.framework` at the same time. Generator without `System_Lazy_T` (or similar name) works on Windows fine.

**Comment by neuecc** [comment]
Thanks, but is this just a legacy NUnit issue?
https://github.com/nunit/nunit/issues/1644
