### ISSUE TITLE
MemoryPackSerializationException: <class> is not registered in this provider.

### ISSUE THREAD

**Issue by invokemethod** [Cysharp/MemoryPack#135]
csproj.

```xml
\<Project Sdk="Microsoft.NET.Sdk">

  \<PropertyGroup>
    \<TargetFramework>net6.0\</TargetFramework>
    \<ImplicitUsings>enable\</ImplicitUsings>
    \<Nullable>enable\</Nullable>
  \</PropertyGroup>

  \<ItemGroup>
    \<PackageReference Include="MemoryPack" Version="1.9.13" />
  \</ItemGroup>
\</Project>
```

test class.

```csharp
using MemoryPack;
namespace MemPackTests {

    [MemoryPackable]
    public partial struct StringTest {

        public StringTest(string? value, int? quality, DateTime? time) {
            this.Value = value;
            this.Quality = quality;
            this.Time = time;
        }

        public string? Value { get; set; }
        public int? Quality { get; set; }
        public DateTime? Time { get; set; }
    }

    [MemoryPackable]
    public partial struct BooleanTest {

        public BooleanTest(bool? value, int? quality, DateTime? time) {
            this.Value = value;
            this.Quality = quality;
            this.Time = time;
        }

        public bool? Value { get; set; }
        public int? Quality { get; set; }
        public DateTime? Time { get; set; }
    }

    [TestClass]
    public class MemoryPackTest {

        [TestMethod]
        public void Serialization() {

            // works
            var bTest = new BooleanTest(true, 0, DateTime.UtcNow);
            var bytes = MemoryPackSerializer.Serialize<BooleanTest>(bTest);
            bTest = MemoryPackSerializer.Deserialize<BooleanTest>(bytes);

            // doesnt work.            
            var sTest = new StringTest("Test", 0, DateTime.UtcNow);
            // throws MemoryPackSerializationException: MemPackTests.StringTest is not registered in this provider.
            bytes = MemoryPackSerializer.Serialize<StringTest>(sTest);
            sTest = MemoryPackSerializer.Deserialize<StringTest>(bytes);
        }
    }
}
```

**Comment by invokemethod** [comment]
tried using an anonymous class to see how it would behave got an interesting error message, note that it works for DPoint<int>, DPoint<bool> just throw this on string.

![image](https://user-images.githubusercontent.com/19761987/227233391-60d28fef-272d-4cf5-a262-d67371bc0ab8.png)

**Comment by jtbrower** [comment]
I thought I would give it a shot; I am running out of Rosyln Pad 17 .Net 7.0.202 and declared a partial class having three public properties with getter/setter methods. There are two string properties and one int property. I instantiate an object and pass it to the MemoryPackSerializer.Serialize method located in MemoryPack 1.9.13 and hit ```MemoryPack.MemoryPackSerializationException.ThrowNotRegisteredInProvider(Type type)``` exception.

I am working on another project right now and during a google search happened by accident upon an article written by the package author that shared the performance, and I thought I would give it a quick go. I suspected my issue might be related to RoselynPad and source generators, but after seeing the others hitting similar issues, I best wait until I have time to dig deeper. The OP of this issue already tried what I was about to do next.

**Comment by neuecc** [comment]
Is it trimming issue?
Change trimming option or don't use it.
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0
