### ISSUE TITLE
Suggestion: Fixed Field Length Control for creating file formats

### ISSUE THREAD

**Issue by KyodaiKen** [Cysharp/MemoryPack#136]
Hi,

I really like this project.

However I miss an easy way to add something like [MemoryPackFieldLength(4)] or so to for example strings. This way it would be possible to add magic words or something into objects. Useful for file formats!

Thank you!

**Comment by neuecc** [comment]
Okay, that is interesting, but it seems to be a bit complicated.
I would like to ask for a dummy field as a work-around.

````
int __dummy_space_for_header; // 4 bytes
```
