### ISSUE TITLE
MemoryPackable(GenerateType.VersionTolerant) MemoryPackOrder - duplicates allowed

### ISSUE THREAD

**Issue by dnarayan** [Cysharp/MemoryPack#141]
Hi - is it possible to add check in the code analysis to find and give errors when there are multiple fields being serialized in a version-tolerant class that are given the same MemoryPackOrder number?

For example, this will serialize/deserialize with no warning:

```csharp
    [MemoryPackable(GenerateType.VersionTolerant)]
    public partial class Tester
    {
        [MemoryPackOrder(0)]
        public int I1 { get; set; }

        [MemoryPackOrder(0)]
        public string S1 { get; set; }

        [MemoryPackOrder(0)]
        public bool B1 { get; set; }
    }
```

... but what comes out after deserialization is incorrect.

**Comment by neuecc** [comment]
thanks, I've added `MEMPACK038 All members order must be unique`.
