### ISSUE TITLE
Serializing/Deserialzing Large Arrays - Length header size is larger than buffer size

### ISSUE THREAD

**Issue by dnarayan** [Cysharp/MemoryPack#142]
Please consider the following code, which crashes upon deserialization with the message: "MemoryPack.MemoryPackSerializationException: 'Length header size is larger than buffer size, length: 100000.'"

```csharp
[MemoryPackable(GenerateType.VersionTolerant)]
public partial class Tester2
{
    [MemoryPackOrder(0)]
    public double[] Vs { get; set; }

    public static void Test()
    {

        var t2 = new Tester2();
        t2.Vs = new double[100_000];

        byte[] bytes;
        using (var writer = new MemoryStream())
        {
            var mp = MemoryPackStreamingSerializer.SerializeAsync(writer, 1, new[] { t2 });
            mp.GetAwaiter().GetResult();
            bytes = writer.ToArray();
        }
        using (var reader = new MemoryStream(bytes))
        {
            var mp = MemoryPackStreamingSerializer.DeserializeAsync<Tester2>(reader, options: MemoryPackSerializerOptions.Utf8);
            var result = mp.ToBlockingEnumerable().First();

            if (!result.Vs.SequenceEqual(t2.Vs))
            {
                throw new Exception();
            }
        }

    }
}
```

What am I missing?

**Comment by neuecc** [comment]
thanks, it is about `MemoryPackStreamingSerializer`'s window size.
StreamingSerializer allocate buffer in default `bufferAtLeast = 4096, int readMinimumSize = 8192`.
This large array's single block size is 800000 so require to expand window size.

`var mp = MemoryPackStreamingSerializer.DeserializeAsync<Tester2>(reader, bufferAtLeast: 810000, readMinimumSize: 1600000, options: MemoryPackSerializerOptions.Utf8);`.

**Comment by dnarayan** [comment]
Thanks @neuecc - the problem with this is that in production, I don't know the size of the data in advance - so I don't know what size to put for bufferAtLeast or readMinSize. 

For example, a user may have serialized something that's 20 doubles long - or 200,000k doubles long - and I want it to work for either case without penalizing the 20-double user. 

At the moment I'm deserializing the entire Stream to byte[], and then calling MemoryPackSerializer.Deserialize - but this means reading the entire object graph (which may have many large arrays) into a huge byte[]. So upon deserialization, I have a byte[] version and a deserialized object graph version, for about double the memory. 

Ideally the deserializer would be able to resize/allocate a larger buffer as necessary based on the data coming in. This would minimize the peak memory usage. 

Did I explain the scenario properly? Is there another way to accomplish this?

**Comment by neuecc** [comment]
While double[] is easy and its size can be calculated, some data structures have unknown block sizes.
You need to decide the maximum capacity of a single item.

**Comment by dnarayan** [comment]
Ah I'm so sorry - I was using the wrong method. I should have been using MemoryPackSerializer.DeserializeAsync<T>(Stream). I really shouldn't have been using MemoryPackStreamingSerializer in my scenario.

Thank you so much for this incredible library!
