### ISSUE TITLE
Field Limit for Classes

### ISSUE THREAD

**Issue by BondiGeek** [Cysharp/MemoryPack#148]
Hi, is the field limit something that could be increased by any chance?

Severity	Code	Description	Project	File	Line	Suppression State
Error	MEMPACK017	The MemoryPackable object <table> member count is '359', however limit size is 249	

We were looking to use MemoryPack along with linq2db and believe it or not we have 3 tables in our db with <= 370 columns.

Thanks,
James

**Comment by neuecc** [comment]
It may be extended to ushort in the future (unions tag is so).
However, currently it will remain as byte (250+reserved flag) for a while.

**Comment by Kiina** [comment]
Just ran into the same issue. Looking through #43 it looks like support is like 99% there. Could there be like a flag implemented that allows for ushort (while being incompatible with the byte version).

Would basically only https://github.com/Cysharp/MemoryPack/blob/main/src/MemoryPack.Core/MemoryPackCode.cs#L11-L19 need to be adjusted or am I missing something?
