### ISSUE TITLE
CustomFormatterAttributes are locked for Unity 2021.2+

### ISSUE THREAD

**Issue by olegpshenin** [Cysharp/MemoryPack#151]
Hello, i am using Unity 2022.2.17f

Currently all CustomFormatterAttributes.cs are locked behind
`#if !UNITY_2021_2_OR_NEWER`
so i can't use any built in custom formatters such as 
`[BrotliFormatter]`

Is it a typo and condition should be opposite or am i missing something because unity 2021.3 seems to be the first at all satisfying required .net versions?

Thanks!

**Comment by neuecc** [comment]
Generic attributes are currently not supported due to C# 11 and above.
We may create a non-generic attribute version, but not at this time.
