### ISSUE TITLE
[BUG] Possible bug with null property?

### ISSUE THREAD

**Issue by jodydonetti** [Cysharp/MemoryPack#152]
I'm using MemoryPack `v1.9.13` with a simple .NET 7 app, and I've found something strange.

This is a minimal reproducible example https://gist.github.com/jodydonetti/c5f7ff7a0a4bfed825548a0f0493ab6d

There's an `ItemMetadata` class which contains just 1 prop as `int X`.

Then there's an `Item<TValue>` class which contains:
- a value prop `TValue Value`
- a timestamp prop as `DateTimeOffset? Moment`
- a metadata prop as `ItemMetadata Metadata`

If I serialize + deserialize an instance of `Item<TValue>` with the `Metadata` prop filled, everything works fine:

![image](https://github.com/Cysharp/MemoryPack/assets/1010086/a4f44e4a-5aa7-479a-ac4e-dd1752380f9b)

But if I do the same with the `Metadata` prop set to `null`, the deserialized `Moment` prop has a different value:

![image](https://github.com/Cysharp/MemoryPack/assets/1010086/95f693ce-1c18-49e3-bd2b-286411894512)

Am I doing something wrong or is this a bug?

Thanks!

**Comment by jodydonetti** [comment]
Hi, thanks for the response!

You mean in the `ItemFormatter<TValue>` class, in the `ItemMetadataFormatter` class or both?

**Comment by jodydonetti** [comment]
Also, should the sample [here](https://github.com/Cysharp/MemoryPack#serialize-external-types) be updated too?

![image](https://github.com/Cysharp/MemoryPack/assets/1010086/e46d5055-2681-4a69-86fc-fcf4bbfe701b)

**Comment by neuecc** [comment]
Yes!
thanks and sorry, updated ReadMe.
