### ISSUE TITLE
Installing version 1.9.14 into Unity using git url couse an error

### ISSUE THREAD

**Issue by IgorTime** [Cysharp/MemoryPack#155]
`Library\PackageCache\com.cysharp.memorypack@cd7a8f71b4\Runtime\MemoryPack.Core\MemoryPackWriter.Unmanaged.cs(1244,349): error CS0103: The name 'Unsafe' does not exist in the current context`

It looks like it can't fing **System.Runtime.CompilerServices.Unsafe.dll** which contains in .unitypackage version

**Comment by neuecc** [comment]
> The dependency managed DLL System.Runtime.CompilerServices.Unsafe/6.0.0 is included with unitypackage. For git references, you will need to add them in another way as they are not included to avoid unnecessary dependencies; either extract the dll from unitypackage or download it from the [NuGet page](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/6.0.0).

**Comment by abenfante** [comment]
Hi! I have the same problem, but I still don't know how to fix it. Can you explain it in more detail?
I'm not very knowlegeable in .net and NuGet
