### ISSUE TITLE
[Enhancement]: implement ICloneable on all MemoryPackable objects OR add .Clone() method to MemoryPackSerializer

### ISSUE THREAD

**Issue by xaroth8088** [Cysharp/MemoryPack#157]
Currently, I implement `ICloneable` on my `[MemoryPackable]`s like so:

```C#
public object Clone()
{
    MyMemoryPackable foo = new();
    MemoryPackSerializer.Deserialize(MemoryPackSerializer.Serialize(this), ref foo);
    return foo;
}
```

This works fine I guess, but it seems like there's probably an opportunity to skip some overhead and potential for error if `ICloneable` came along for free whenever I used `[MemoryPackable]`.

If you're not a fan of semi-secretly implementing interfaces like that, I could definitely see a new `Clone()` method that I'd use like this instead:
```C#
public object Clone()
{
    return MemoryPackSerializer.Clone(this);
}
```

**Comment by neuecc** [comment]
serializer is not best solution for clone.

**Comment by dnarayan** [comment]
@xaroth8088 

Why not just add an extension method? I have this in my codebase:

```
public static class SerializationHelpers
{
    public static T CloneWithSerialization<T>(this T a)
    {
        var sA = MemoryPackSerializer.Serialize(in a);
        return MemoryPackSerializer.Deserialize<T>(sA);
    }
}
```
