### ISSUE TITLE
Aspnet Core Return Type

### ISSUE THREAD

**Issue by alberk8** [Cysharp/MemoryPack#160]
Is it possible to decorate certain http method within a controller to always return json instead of memorypack format?.

**Comment by neuecc** [comment]
If you want to do it at the OutputFormatter level, you could check [OutputFormatterCanWriteContext](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.outputformattercanwritecontext?view=aspnetcore-7.0) in bool CanWriteResult.
Also, I'm sure there are other configuration techniques, but that's for ASP .NET, not MemoryPack.

**Comment by alberk8** [comment]
> If you want to do it at the OutputFormatter level, you could check [OutputFormatterCanWriteContext](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.outputformattercanwritecontext?view=aspnetcore-7.0) in bool CanWriteResult. Also, I'm sure there are other configuration techniques, but that's for ASP .NET, not MemoryPack.

Is it possible to have a Custom Attribute ` [MemoryPackEnable] ` for the Controller or Method, so that I can have a mix and match of json or memorypacked  method in the same controller?
