### ISSUE TITLE
Not able to use MemoryPackAllowSerialize on a record parameter

### ISSUE THREAD

**Issue by espenrl** [Cysharp/MemoryPack#162]
![image](https://github.com/Cysharp/MemoryPack/assets/4621581/93aa95c7-8f55-4125-b19f-d79edb009e21)

I guess `MemoryPackAllowSerializeAttribute` must be defined with `AttributeTargets.Parameter`.

**Comment by neuecc** [comment]
please use `[property:MemoryPackAllowSerialize]`.

`public sealed partial record Feature([property:MemoryPackAllowSerialize]Geometry geometry);`

**Comment by espenrl** [comment]
Thanks @neuecc, I've learned something new today
