### ISSUE TITLE
MemoryPackIgnore not working in unmanaged structs?

### ISSUE THREAD

**Issue by Danon5** [Cysharp/MemoryPack#163]
Hey, just downloaded the package. Love all the options. However, the first thing I am using it for is serializing unmanaged structs.

If I create a TestStruct with three public int fields, for example, and give one of them the [MemoryPackIgnore] attribute, the deserialized version will still have the data from the field I wanted to ignore. If I copy paste the code but change TestStruct to a TestClass, the attribute works as expected. It also works as expected if I add a packable reference type into the struct, causing it to become managed.

I read that unmanaged structs are serialized using the underlying data directly, so maybe this is intended behavior? If so, is there a way to force some other method of serialization to get around this?

I am trying to synchronize unmanaged structs over the network by only applying the non-ignored values.

**Comment by neuecc** [comment]
Yes, unmanaged structs write memory data directly, so no configuration works at all.
This is a trade-off for performance and there is no room for change.
If you want to serialize only some values in a struct, transfer the values to another struct.
