### ISSUE TITLE
" ___object___ is not registered in this provider" exception when trying to serialise objects

### ISSUE THREAD

**Issue by keshavshankar08** [Cysharp/MemoryPack#164]
MemoryPack serialization/deserialization works for basic variables (strings, lists, etc.). Once an object var is used (record, class, etc.), I get "__________ is not registered in this provider". I am not sure if this is a System issue or an incorrect usage of MemoryPack. Additionally, I checked my Dependencies > Analyzers, and "MemoryPack.Generator" is not creating any files...

----------
**Here is my sample project where this issue occurs:** 

### Exception:  _"MemoryPack.MemoryPackSerializationException : System.Object is not registered in this provider."_

- Serializer.cs
```csharp
public interface SerializerInterface
{
    MemoryStream Serialize(object unpacked);

    object Deserialize(MemoryStream packed);
}

public class Serializer : SerializerInterface
{
    public Serializer()
    {
    }

    public MemoryStream Serialize(object unpacked)
    {
        return new MemoryStream(MemoryPackSerializer.Serialize(unpacked));
    }

    public object Deserialize(MemoryStream packed)
    {
        return MemoryPackSerializer.Deserialize<object>(packed.ToArray());
    }

}
```
- SerializerTest.cs
```csharp
public class SerializerTest
{
    [Fact]
    public void SerializeAndDeserialize()
    {
        // arrange.
        TestEvent e = new(1, "Test 1");
        SerializerInterface serializerObj = new Serializer();

        // act.
        MemoryStream packed = serializerObj.Serialize(e);
        object unpacked = serializerObj.Deserialize(packed);

        // verify.
        Assert.Equal(e, unpacked);
    }
    [MemoryPackable]
    public partial record TestEvent(int Id, string Message) ;
}
```

**Comment by neuecc** [comment]
object is not supported by default.
A custom formatter can be provided to add support, but we have no intention of including it in the standard.
