### ISSUE TITLE
Can I serialize items one by one and deserialize as a collection?

### ISSUE THREAD

**Issue by zorgoz** [Cysharp/MemoryPack#165]
Hello,

I am implementing a caching mechanism for measurement data, I have previously used MemoryPack to store "header" data and "items" in a single class. That meant however, that I was always keeping all the items in a lot in memory and serialize-deserialize them in a single shot. But I need to be able to store the items by appending to the file. How does MemoryPack handle collections? Can I simply write the header (supposing it has a fixed size), then append each item serialized with MemoryPack and afterwards, when reading back, just read the items as an enumerable starting from after the header's ending position? The items might contain strings. Hence the size of it is not fixed. "Advanced" version: can I use a class derived from the header to read the items together with the header?
e.g.:

```csharp
public class Header // used for writing/updating header only
{
...
}

public class ReadHeader: Header // used to read the whole file in one shot
{
 public ICollection<Item> Items { get; set; }
}
```

Thank you

**Comment by neuecc** [comment]
There is a collection in the binary specification. 
https://github.com/Cysharp/MemoryPack#collection
It has length as a header, and after reading it, Deserialize the length times T.
Any content would be treated as a collection if written to the same specifications.
