### ISSUE TITLE
Destination is too short

### ISSUE THREAD

**Issue by kayhustle** [Cysharp/MemoryPack#172]
I am using MemoryPack 1.9.16
Trying to serialize a dictionary via the following code 
MemoryPackSerializer.Serialize<T>(data)
and getting the following exception:
System.ArgumentException: 'Destination is too short. (Parameter 'destination')'
   at System.ThrowHelper.ThrowArgumentException_DestinationTooShort()
   at MemoryPack.Internal.ReusableLinkedArrayBufferWriter.ToArrayAndReset()
   at MemoryPack.MemoryPackSerializer.Serialize[T](T& value, MemoryPackSerializerOptions options)

Any help would be appreciated.
Thanks

**Comment by neuecc** [comment]
please provide reproducable code.

**Comment by DevAlphaFox** [comment]
I am using MemoryPack 1.10.0 and getting the same error when trying to serialize the class below called GlobalHistory, which contains 2,000 list items.

When I reduce the number of items to 710, the exception changes to an OverflowException, "Arithmetic operation resulted in an overflow". Either way, the stack trace points to the same location: "at MemoryPack.Internal.ReusableLinkedArrayBufferWriter.ToArrayAndReset() at MemoryPack.MemoryPackSerializer.Serialize[T](T& value, MemoryPackSerializerOptions options)"

It eventually works, however, when I further reduce the number of items to 705, which produces an expected 2.085 GB file. 

-------------------------------------------------------------
```
[MemoryPackable(GenerateType.Collection)]
public partial class GlobalHistory : List<DataPointHistory> {
}

[MemoryPackable(GenerateType.Collection)]
public partial class DataPointHistory : List<DataPoint> {
}

```

**Comment by hadashiA** [comment]
There is a limit to the size of a sequence of bytes that can be held in memory at one time.
This is a limitation of C#. (The limit on the number of elements in a byte[] is probably int.MaxValue, so about 2GB.)

BTW, 2GB is too large to handle in memory and not efficient at all.

Instead, use MemoryPackStreamingSerializer.

e.g)
```cs
await MemoryPackStreamingSerializer.SerializeAsync(stream, list.Count, list);
```
