### ISSUE TITLE
TypeScript generator trying to import abstract class with nogenerate causes error

### ISSUE THREAD

**Issue by omurefeguclu** [Cysharp/MemoryPack#174]
**Steps to reproduce:**

1. Create an abstract class with [MemoryPackable(GenerateType.NoGenerate)] attribute
```
    [MemoryPackable(GenerateType.NoGenerate)]
    public abstract partial class BaseEntityDto<TEntity> : IMapped<TEntity>
        where TEntity : BaseEntity
    {
        [IgnoreAsSource]
        public virtual string Id { get; set; }
    }
```

2. Create a class that extends from abstract class we just generated
```
    [MemoryPackable]
    [GenerateTypeScript]
    public partial class ExerciseDto : BaseEntityDto<Exercise>
    {
        public int Difficulty { get; set; }
    }
```

**Expected Behavior:**
Abstract class should have been ignored by SourceGenerator

**Actual Behavior:**
Abstract class is trying to be imported from typescript file of inherited class. As such file doesn't exist it causes an error.

![image](https://github.com/Cysharp/MemoryPack/assets/51865067/14eb3876-f723-4a3a-b06b-776a17c925d2)

**Comment by hadashiA** [comment]
This seems resolved in #175.
