### ISSUE TITLE
Would it be an idea to add LZ4 compression?

### ISSUE THREAD

**Issue by mwijnands** [Cysharp/MemoryPack#179]
As MessagePack has LZ4 compression built-it, could you also include that here? The implementation of LZ4 in MessagePack is faster than LZ4.Net (which I am using now). Brotli is slower than LZ4 even in the Fastest CompressionLevel, but has smaller size. LZ4 has perfect balance for my usecase.

I have looked into the LZ4 implementation in MessagePack to see if I can add it to MemoryPack, but I am having a hard time with it.

**Comment by neuecc** [comment]
I am making compression library, it will release soon(maybe this month).
https://twitter.com/neuecc/status/1678588727797612544
