### ISSUE TITLE
Strange Ref keyword error

### ISSUE THREAD

**Issue by srdjo** [Cysharp/MemoryPack#181]
Hi all,

as of this morning I am getting the strange error on this part of generated code

`global::MemoryPack.Formatters.ListFormatter.SerializePackable(ref tempWriter, ref System.Runtime.CompilerServices.Unsafe.AsRef(value.@KolabCit)); offsets[16] = tempWriter.WrittenCount;`

Error in file MemoryPackFormatter.g.cs is

Error	CS1620	Argument 1 must be passed with the 'ref' keyword 

I am serializing a simple class

```csharp
[DataContract, MemoryPackable(GenerateType.VersionTolerant, SerializeLayout.Sequential)]
public partial class ObavezeDTO
{

    public string KolabId { get; set; }
    public string? KolabNaziv { get; set; }
   

    public List<KolabCitanjeDTO> KolabCit { get; set; } = new List<KolabCitanjeDTO>();

    public List<KolabKomentariDTO> Komentari { get; set; } = new List<KolabKomentariDTO>();

}
```

What might be the problem ?

I did not change any code but i did install a new .Net. I was using .Net 8 preview 7 without any problems and yesterday I installed new .Net 8 RC1

**Comment by srdjo** [comment]
Reverting back to .Net 8 Preview 7 fixes the problem

Any info about the next release that supports .Net RC1 ?

**Comment by neuecc** [comment]
Thanks for the interesting report.
I will check it out with RC1.

**Comment by neuecc** [comment]
sorry, I can't reproduce it(using Visual Studio 2022 17.8.0 preview 2.0).

**Comment by srdjo** [comment]
I can confirm that after upgrading VS from 17.8.0 preview 1.0 to 17.8.0 preview 2.0 and installing .Net 8 RC1 the error is gone.
