### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [Cysharp/MemoryPack#183]
Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/memorypack/api/MemoryPack.html

This is ready-to-go, so above link can be added to README for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/memorypack/api/MemoryPack.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/memorypack/api/MemoryPack.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by hadashiA** [comment]
Thanks for letting me know.
However, this repo seems to be a documentation where the README text is rather more important than the API reference.
