### ISSUE TITLE
Upgrading a VersionTolerant Model

### ISSUE THREAD

**Issue by dnarayan** [Cysharp/MemoryPack#185]
If you have something like this already serialized:

```
[MemoryPackable(GenerateType.VersionTolerant)]
public partial class Model
{
[MemoryPackOrder(0)]
public string Name { get; set; }
}
```

Then lets say you need to upgrade the model by adding an additional property, but you want the new property to have non-default value, like this:

```
[MemoryPackable(GenerateType.VersionTolerant)]
public partial class Model
{
[MemoryPackOrder(0)]
public string Name { get; set; }

[MemoryPackOrder(1)]
[DefaultValue(99)]
public int Age { get; set; } = 99;
}
```

So when the original model is deserialized the value of Age should be 99 even though this was not in the original byte[]. Is there any way to do that? (I showed how I'd do it with Protobuf-net, but this does not seem to work in Memorypack.)

Thanks!

**Comment by hadashiA** [comment]
Hello. There seems to be a problem as you have pointed out.
In #242, I tried to fix deriving default values from C# type definitions.
Thanks a lot.

**Comment by hadashiA** [comment]
The feature to detect default values was problematic and was reverted.
We would like to consider another method.

**Comment by hadashiA** [comment]
Hello.

Before, we tried to take care of all default values, but it is hard to deal with all cases and there were performance problems.
Also, this problem only occurs when the binary is old.

In the end, we only addressed it by adding an attribute for cases where you want to handle a special default value.

Please check `[SuppressDefaultInitialization]` added in [1.21.0](https://github.com/Cysharp/MemoryPack/releases/tag/1.21.0).
https://github.com/Cysharp/MemoryPack?tab=readme-ov-file#version-tolerant

```cs
[MemoryPackable].
public partial class DefaultValue
{
    public string Prop1 { get; set; }

    [SuppressDefaultInitialization].
    public int Prop2 { get; set; } = 111; // < if old data is missing, set `111`.
    
    public int Prop3 { get; set; } = 222; // < if old data is missing, set `default`.
}
```

For members with this attribute, the default value of the type declaration can be used.
