### ISSUE TITLE
Deserialize Exception 'T is failed in provider at creating formatter.' at NativeAOT 

### ISSUE THREAD

**Issue by dameng324** [Cysharp/MemoryPack#189]
I found the main issue is The T's static constructor does not Invoke when `Deserialize<T>` when NativeAOT. so there is no formatter registered. If I add `var r = new MemPackTestObj() { Strings = new[] { "a", "b", "c" } };` before Deserialize, It works.

Code:
```cs
using MemoryPack;
using System.Runtime.InteropServices;

Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");

//var r = new MemPackTestObj() { Strings = new[] { "a", "b", "c" } };
//var bytes = MemoryPackSerializer.Serialize(r);

var bytes = Convert.FromBase64String("AwMAAAD+////AQAAAGH+////AQAAAGL+////AQAAAGMAAAAAAAAAAP////8=");
Console.WriteLine(Convert.ToBase64String(bytes));
var r2 = MemoryPackSerializer.Deserialize<MemPackTestObj>(bytes);
foreach (var s in r2!.Strings)
{
    Console.WriteLine(s);
}

[MemoryPackable]
public partial record MemPackTestObj
{
    public string[] Strings { get; set; }
    public DateTime Date { get; set; }
    public string Name { get; set; }
}
```
csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>

        <!-- AOT Options -->
        <!-- https://learn.microsoft.com/ja-jp/dotnet/core/deploying/native-aot/ -->
        <PublishAot>true</PublishAot>
        <SelfContained>true</SelfContained> 
        <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
        <IlcOptimizationPreference>Size</IlcOptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="MemoryPack" Version="1.9.16" />
    </ItemGroup>
</Project>
```

When `dotnet run -c Release` It works as expected.
```
.NET 8.0.0-rc.2.23479.6
AwMAAAD+////AQAAAGH+////AQAAAGL+////AQAAAGMAAAAAAAAAAP////8=
a
b
c
```
When `dotnet publish -c Release` and `.\bin\Release\net8.0\win-x64\publish\NativeAot.exe`
```
.NET 8.0.0-rc.2.23479.6
AwMAAAD+////AQAAAGH+////AQAAAGL+////AQAAAGMAAAAAAAAAAP////8=
Unhandled Exception: MemoryPack.MemoryPackSerializationException: MemPackTestObj is failed in provider at creating formatter.
 ---> System.InvalidOperationException: Type implements IMemoryPackFormatterRegister but can not found RegisterFormatter. Type: MemPackTestObj
   at MemoryPack.MemoryPackFormatterProvider.TryInvokeRegisterFormatter(Type) + 0xe9
   at MemoryPack.MemoryPackFormatterProvider.Cache`1..cctor() + 0x51
   --- End of inner exception stack trace ---
   at MemoryPack.MemoryPackSerializationException.ThrowRegisterInProviderFailed(Type, Exception) + 0x4a
   at MemoryPack.ErrorMemoryPackFormatter`1.Throw() + 0x2f
   at MemoryPack.MemoryPackSerializer.Deserialize[T](ReadOnlySpan`1, T&, MemoryPackSerializerOptions) + 0xf0
   at Program.<Main>$(String[] args) + 0x8e
   at NativeAot!<BaseAddress>+0x172ee0
```

Is this a NativeAOT runtime bug? any solution to solve this?

**Comment by dameng324** [comment]
https://github.com/Cysharp/MemoryPack/blob/9aa51ce1e8da24e27053bf2448c127c4263c2096/src/MemoryPack.Core/MemoryPackFormatterProvider.cs#L177-L197

Maybe the main point is here. dotnet -c Release has reflection metadata. but NativeAOT has not.

static method is not invoked at `dotnet run -c Release`, the `TryInvokeRegisterFormatter` method invoked.

It looks like a MemoryPack issue not NativeAOT runtime bug.

**Comment by hadashiA** [comment]
Hello. Thanks for the report.

It seems that if there is no Serialize in the source code and only Deserialize, the AOT build will trim the required code.

As a quick workaround, we have addressed this issue by adding [DynamicallyAccessedMembers].

It is difficult to completely remove reflection from a MemoryPack implementation.
Therefore, we are currently unable to even turn off all the AOTwarnings that the compiler produces.

But for the time being, adding attribute seems to work in most cases.

Next release should be coming soon.
Please let us know if there are any more problems. Thanks again.

**Comment by dameng324** [comment]
Thanks for your work. It looks useful in the case.

I wonder `Deserialize<ICollection<MemPackTestObj>>` will work or not.

**Comment by dameng324** [comment]
> I wonder Deserialize<ICollection<MemPackTestObj>> will work or not. I'll try until have some time to do it.

I have tried and it works. Looks very nice.

**Comment by Nolram12345** [comment]
I'm running into this issue again and again at the moment - any info on how to address this? What is required to allow deserialisation without a serialize function being used in the assembly?

**Comment by BlameTwo** [comment]
@Nolram12345 

You can try to manually register the serializer.


``` csharp
 MemoryPackFormatterProvider.Register<RecordCardItemWrapper>();
 MemoryPackFormatterProvider.Register<RecordCacheDetily>();
 MemoryPackFormatterProvider.Register<WavesAnalysisPlayerCard>();
 MemoryPackFormatterProvider.Register<WavesAnalysisPlayerCardItem>();
 MemoryPackFormatterProvider.Register<Datum>();
 MemoryPackFormatterProvider.Register<LocalAccount>();
```

**Comment by Nolram12345** [comment]
The problem I have is that I don't have central access to the all the types, so I can't manually register them. I'd need to collect all relevant types first somehow.

I've solved the problem by just writing my own source generated binary serialiser as part of another subsystem instead of using MemoryPack.

**Comment by dameng324** [comment]
I use [LightProto](https://github.com/dameng324/LightProto)
instead. which has no trimming warnings and no worries about trimming will broke my application.
