### ISSUE TITLE
Unity 2021.3.31f - Unit Test Failing - Class Defined in Editor Assembly is not registered in this provider

### ISSUE THREAD

**Issue by shasheppard** [Cysharp/MemoryPack#190]
If you take the attached MemoryPackTests.txt file (change extension txt to cs) and run the MemoryPackTests.TestMemoryPack_Plain method in the TestRunner as-is it will fail with this error:
[MemoryPackTests.txt](https://github.com/Cysharp/MemoryPack/files/13061762/MemoryPackTests.txt)

> TestMemoryPack_Plain (0.006s)
> ---
> MemoryPack.MemoryPackSerializationException : Assets.Editor.UnitTests.MemoryPack.Something is not registered in this provider.
> ---
> at MemoryPack.MemoryPackSerializationException.ThrowNotRegisteredInProvider (System.Type type) [0x00000] in D:\projects\unity\gonet_sample_games\gonet-fps\Library\PackageCache\com.cysharp.memorypack@9aa51ce1e8\Runtime\MemoryPack.Core\MemoryPackSerializationException.cs:84 
>   at MemoryPack.ErrorMemoryPackFormatter`1[T].Throw () [0x00032] in D:\projects\unity\gonet_sample_games\gonet-fps\Library\PackageCache\com.cysharp.memorypack@9aa51ce1e8\Runtime\MemoryPack.Core\MemoryPackFormatterProvider.cs:453 
>   at MemoryPack.ErrorMemoryPackFormatter`1[T].Serialize (MemoryPack.MemoryPackWriter& writer, T& value) [0x00000] in D:\projects\unity\gonet_sample_games\gonet-fps\Library\PackageCache\com.cysharp.memorypack@9aa51ce1e8\Runtime\MemoryPack.Core\MemoryPackFormatterProvider.cs:432 
>   at MemoryPack.MemoryPackSerializer.Serialize[T] (T& value, MemoryPack.MemoryPackSerializerOptions options) [0x00062] in D:\projects\unity\gonet_sample_games\gonet-fps\Library\PackageCache\com.cysharp.memorypack@9aa51ce1e8\Runtime\MemoryPack.Core\MemoryPackSerializer.Serialize.cs:88 
>   at Assets.Editor.UnitTests.MemoryPack.MemoryPackTests.TestMemoryPack_Plain () [0x00021] in D:\projects\unity\gonet_sample_games\gonet-fps\Assets\GONet\Code\GONet\Editor\UnitTests\GONet\MemoryPack\MemoryPackTests.cs:40 
>   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <afe256a0391e468fbcdb82154daad696>:0

It seems like the generated code is not being included during the unit test execution for some reason.  Although, I  can see that the generated code does exist...for example, in visual studio pressing F12 on the Something partial class I wrote, it yields:
<img width="801" alt="image" src="https://github.com/Cysharp/MemoryPack/assets/4544796/89d47841-b560-4286-8514-7a1bd3c72ea6">

If I want the unit test to pass, I cut and pasted some of the generated code into my unit test file and wrapped it all with a preprocessor directive...so, to make this "work" just to see, you can uncomment the first line of MemoryPackTests.txt to define:

> #define SHAUN_MEMORY_PACK_GEN_IS_MESSING_UP

I have some other code that runs in the editor that utilizes MemoryPack and fails in the same way  (i.e., with the "MemoryPack.MemoryPackSerializationException : <class> is not registered in this provider." error).  So, I am wondering if this is an issue with editor or not or just what should be done to overcome this.  Thank you!

**Comment by shasheppard** [comment]
By the way, this is not just an editor/unit test thing as the same error occurs when attempting to serialize MemoryPackable objects in game as well.  I see other similar issues, but not quite the same...so, I am continuing to look into it. It seems like other folks have used MemoryPack with Unity successfully though, so it seems like I am just missing something basic. 

The “RoslynAnalyzer” label is applied properly to the MemoryPack.Generator.Roslyn3.dll and the things mentioned in Unity docs (https://docs.unity3d.com/Manual/roslyn-analyzers.html) all seem to have been accounted for.  The fact that the generated classes exist in Visual Studio says things are mostly occurring as they should.  No idea why they would not be available upon execution though (i.e., unit test or play mode of the game).

**Comment by shasheppard** [comment]
I figured that since other folks seem to be running Unity with MemoryPack without this type of issue I should try another version of Unity and see how it goes.  I upgraded the project from 2021.3.31f1 to 2022.3.12f1 and ..... the unit test passed!  So, I am not sure if this issue should be considered resolved or not.

**Comment by hadashiA** [comment]
Thank you for your report.

MemoryPack 1.20.0 brings the Unity support version up to 2022.3, and changes the way the source generator dll is distributed.

Therefore, according to your investigation, it may possibly not reproduce.

If you have problems with the latest version, you are welcome to reopen Thanks a lot.
