### ISSUE TITLE
Nesting / How to deal with trimming issues

### ISSUE THREAD

**Issue by HighPerfDotNet** [Cysharp/MemoryPack#194]
Hi!

First of all - BIG thanks for making real great working software, this is how Microsoft should have done it in the first place with BinaryFormatter.

There are only a couple of issues that I was wondering about - Googling wasn't showing enough info, so I thought it might benefit other users who will be searching for solutions.

1) Nested classes - 

_Error	MEMPACK002	The MemoryPackable object '???' must be not nested type_	

I worked that around by unnesting them, but ideally would have preferred to avoid it (having said that this is cheap enough price to pay for this real solution to my problem), is there a fundamental issue that makes it impossible from having them serialised? BinaryFormatter did not have any issues with them (but obviously it used Reflection), I would have thought source generators would be able to handle this too?

2) Due to complex project I had to use unions - 

[MemoryPackUnionFormatter(typeof(ClassA))]
[MemoryPackUnion(0,typeof(ClassA_B))]
[MemoryPackUnion(1,typeof(ClassA_C))]
public partial class ClassA_Formatter
{
}

This solved my problem, thank you for offering this option, but manually maintaining the list with unique numbers feels rather unelegant and prone to errors, is there a fundamental reason why it had to be done manually, limitation of source generation? I assume so, but would be nice to know a few more details.

Finally those of us who want to use this great library in self-contained files and especially Native AOT that requires trimming, here is the solution for some inevitable trimming issues - adding to project file keeps trimmer at bay and saves the day!

  <ItemGroup>
  <TrimmerRootAssembly Include="MemoryPack.Core" />
  </ItemGroup>

Thanks again for great work, this really needs to be picked up by Microsoft and added to .NET core!

**Comment by neuecc** [comment]
Thanks.

> 1. Nested classes

In fact, there is no problem.
They just skimp on nested type handling when generating the source code.
So it's not impossible to handle.

> 2. Due to complex project I had to use unions

Manual attachment avoids the possibility of errors.
Automatic numbering is vulnerable to increases and decreases.
