### ISSUE TITLE
If the length of the serialized byte array exceeds 65536, it won't be correctly deserialized.

### ISSUE THREAD

**Issue by KazuhiroNomura** [Cysharp/MemoryPack#195]
When deserializing beyond byte[65536], the reader.Options values are set to their default values, which are Options.ServiceProvider = null and Options.StringEncoding = Utf8.

The cause of this issue is that the MemoryPackSerializer class's 
```csharp
public static T? Deserialize<T>(in ReadOnlySequence<byte> buffer, MemoryPackSerializerOptions? options = default)
        T? value = default;
        Deserialize<T>(buffer, ref value);
        return value;
    }
````

method you mentioned doesn't use the options argument. This is why the reader.Options values are set to their default values when deserializing data beyond a certain size, as the options argument is not being considered in the deserialization process.

**Comment by neuecc** [comment]
thanks, it seems critical bug, should fix soon.
