### ISSUE TITLE
MemoryPack.MemoryPackSerializationException : <class> is not registered in this provider

### ISSUE THREAD

**Issue by RandallFlagg** [Cysharp/MemoryPack#198]
I had an issue in my code that raised the error:

> MemoryPack.MemoryPackSerializationException : <class> is not registered in this provider

After some digging I found the reason for it to be because I forgot to mark one of the classes with the `[MemoryPackable]`.
I think there should be a more specific error for this situation **e.g.**
> MemoryPack.MemoryPackSerializationException: 'MemPackTestObj2 is not marked as MemoryPackable.'.

**Example:**
**Example Program (Program.cs):**
```
using MemoryPack;

var pat = new MemPackTestObj2();
pat.Name = "b";
var r = new MemPackTestObj1() { Name = "a", MyList = new List<MemPackTestObj2> { pat } };
var bytes = MemoryPackSerializer.Serialize(r);

[MemoryPackable]
public partial record MemPackTestObj1
{
    public string Name { get; set; }
    public IList<MemPackTestObj2> MyList;
}

//[MemoryPackable] //Uncomment to fix the exception
public partial record MemPackTestObj2
{
    public string Name { get; set; }
}
```

**Example Project File (exception.csproj):**
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="MemoryPack" Version="1.9.16" />
    </ItemGroup>
</Project>
```

**The exception received when running the code:**
> MemoryPack.MemoryPackSerializationException: 'MemPackTestObj2 is not registered in this provider.'

**Comment by neuecc** [comment]
That is correct.
If it is used for a FIELD type, it is parsed, but as for the GENERIC types, it seems to be out of the analysis.
However, theoretically, the type of generics does not necessarily indicate the serialization target, though. ......

**Comment by RandallFlagg** [comment]
If you think it is not right or much of a hassle, then the message can be altered to be something a bit more verbose that will reflect the source of the error. something like this:

> MemoryPack.MemoryPackSerializationException : <class> is not registered in this provider (Check that you marked all the classes with MemoryPackable or something else or another thing (happened for the field` IList<MemPackTestObj2> MyList`))

**Comment by neuecc** [comment]
The error message is already telling you that there is a problem with MemPackTestObj2, right?

**Comment by RandallFlagg** [comment]
No, the error I saw was `MemoryPack.MemoryPackSerializationException : is not registered in this provider`. There is no mention of the obj name or the field name.

**Comment by neuecc** [comment]
You say
> MemoryPack.MemoryPackSerializationException: 'MemPackTestObj2 is not registered in this provider
