### ISSUE TITLE
char[] array cannot be serialized or deserialized.

### ISSUE THREAD

**Issue by KazuhiroNomura** [Cysharp/MemoryPack#199]
```csharp
    [Fact]
    public void MemoryPackでCharArray(){
        MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<char>());
        var input=new[]{`a`,`b`,`c`};
       var bytes=MemoryPackSerializer.Serialize(input);
        var output=MemoryPackSerializer.Deserialize<char[]>(bytes);
        Assert.True(input.SequenceEqual(output));
    }
```

char[] array cannot be serialized or deserialized.

`MemoryPackSerializer` class
`public static byte[] Serialize<T>(in T? value, MemoryPackSerializerOptions? options = null)`method
`case TypeHelpers.TypeKind.UnmanagedSZArray:`
size is 1
`MemoryPackReader` class
`public void DangerousReadUnmanagedArray<T>([System.Runtime.CompilerServices.ScopedRef] ref T[]? value)` method
`Unsafe.SizeOf<T>()` returns 2.
Therefore, it seems that it cannot be processed correctly.

char[]配列がシリアライズ、デシリアライズできません。
`MemoryPackSerializer`クラスの
`public static byte[] Serialize<T>(in T? value, MemoryPackSerializerOptions? options = null)`メソッドの
`case TypeHelpers.TypeKind.UnmanagedSZArray:`の
`size`が1になっています
`MemoryPackReader`クラスの
`public void DangerousReadUnmanagedArray<T>([System.Runtime.CompilerServices.ScopedRef] ref T[]? value)`メソッドの
`Unsafe.SizeOf<T>()`が2を返します。
そのため正しく処理できないようです。

**Comment by neuecc** [comment]
thanks, fixed and released 1.10.0.
