### ISSUE TITLE
Net 6 Support

### ISSUE THREAD

**Issue by lsylusiyao** [Cysharp/MemoryPack#2]
Hello, this is a pretty good project for dotneters.  However, since Net6 is the newest LTS, is there any possibility of adding support for Net6 with the help of other packages? Thanks.

**Comment by roubachof** [comment]
man, it's in the readme:

> It is also a completely new design utilizing .NET 7 and C# 11 and the Incremental Source Generator.

**Comment by sgf** [comment]
> Hello, this is a pretty good project for dotneters. However, since Net6 is the newest LTS, is there any possibility of adding support for Net6 with the help of other packages? Thanks.

its Base .net 7 and C# 11,pls close the issue.

**Comment by neuecc** [comment]
I've started to create .NET Standard 2.1 support #27
