### ISSUE TITLE
Example how to Serialize to string then from string orginal data

### ISSUE THREAD

**Issue by guillaume-chervet** [Cysharp/MemoryPack#203]
Hi Thank you for your awseome library.

I am not good at writing optimized code in C#. 
I would like to know what is the best way to serialize an object to string.

I do not manage to make it works.

```C#
var bytes = MemoryPackSerializer.Serialize(data});
// then convert to string
string dataString = ...
// then serialize back to bytes
var finalBytes = ... // From string
var finalData = MemoryPackSerializer.Deserialize<DataType>(bytes)
```

Other question, do you have a sample how to make an HTTP client POST a bytes array (for example a multipart form data) to an C# API and how to read it back and convert it back to the original data inside ASP.NET Core ?

**Comment by hadashiA** [comment]
Hi,

> I would like to know what is the best way to serialize an object to string.

Officially, we do not provide any views as string format.

Therefore, please consider the common method of encoding binaries into strings.
For example, the standard lib has `Convert.ToBase64String`.

> Other question, do you have a sample how to make an HTTP client POST a bytes array 

Seems like a basic topic that is off topic for this repo. Also, I think it depends on the framework you are using, so I will just suggest the following here.

- If you want to use multipart form data, it might be more common to encode binaries in base64.
- Alternatively, binaries can be sent and received in the HTTP body. In that case, use Content-Type such as `application/octet-stream`.   If you want to send binary data via API, octet-stream may be suitable.
 
You can probably find samples by looking up these keywords.

**Comment by hadashiA** [comment]
Sorry, I forgot to mention. Officially, we provide `MemoryPack.AspNetCoreMvcFormatter`  package, which may be helpful if you are using ASP .NET Core. thanks.
