### ISSUE TITLE
Confusing wording in the README.md

### ISSUE THREAD

**Issue by AldeRoberge** [Cysharp/MemoryPack#205]
"Unity version's MemoryPack does not compatible with .NET MemoryPack in NuGet so can't do creating netstandard 2.1 dll in .NET and use in Unity."

I wanted to contribute to fixing some typos in the readme, but I'm not even sure to know what to make of this sentence

**Comment by laicasaane** [comment]
The version of MemoryPack that can be used in Unity and the version distributed on NuGet are not compatible with each other. So .dlls produced from a standard csproject targetting "netstandard 2.1" cannot be used within Unity environment. Instead, one can just put the source code directly into Unity.

I hope my explanation makes sense to you.

**Comment by hadashiA** [comment]
Hello.
MemoryPack's Unity support will be changed to dll distribution via NuGetForUnity instead of source code packages.
Therefore, the incompatibility mentioned here is likely to be resolved. The README is also expected to be corrected in the next release.  Thanks!
