### ISSUE TITLE
FluentAPI support?

### ISSUE THREAD

**Issue by MagicAndre1981** [Cysharp/MemoryPack#21]
In the[ readme you](https://github.com/Cysharp/MemoryPack#quick-start) explain that we need to add `[MemoryPackable]` attribute. I want to avoid this and have clean classes and add such thing via [FluentAPI like EF](https://www.entityframeworktutorial.net/efcore/fluent-api-in-entity-framework-core.aspx) does. Is this already supported or will this be supported?

**Comment by neuecc** [comment]
FluentAPI is for dynamic configuration.
This is not suitable for Source Generator.
No additions are planned.
