### ISSUE TITLE
 C# Generic class support

### ISSUE THREAD

**Issue by Zsss** [Cysharp/MemoryPack#212]
code:
```
using MemoryPack;

[MemoryPackable]
[MemoryPackUnion(0, typeof(IntAttr))]
[MemoryPackUnion(1, typeof(FloatAttr))]
public partial interface IAttr : IAttrBase
{
    
}

public interface IAttrBase
{
    
}

public interface IObjectPool
{
    
}

[MemoryPackable]
[MemoryPackUnionFormatter(typeof(IAttr))]
public abstract partial class ZAttr<T> : IAttr,IObjectPool
{
    
}

[MemoryPackable]
public partial class IntAttr : ZAttr<int>
{
    
}

[MemoryPackable]
public partial class FloatAttr : ZAttr<float>
{
    
}

```

error:
MemoryPack.Generator.Roslyn3\MemoryPack.Generator.MemoryPackGenerator\ZAttr_T_.MemoryPackFormatter.g.cs(91,79): error CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?)

MemoryPack.Generator.Roslyn3\MemoryPack.Generator.MemoryPackGenerator\ZAttr_T_.MemoryPackFormatter.g.cs(91,69): error CS0144: Cannot create an instance of the abstract type or interface 'ZAttr<T>'

**Comment by qufangliu** [comment]
mark

**Comment by hadashiA** [comment]
Hi. There seems to be a misunderstanding of usage.
`MemoryPackUnionFormatter` is an option when the base type cannot be given a `MemoryPackUnion` directly.

Your example works by removing the attributes from `ZAttr<T>`.

( If that is not what you want to do, I would appreciate it if you could tell me how you use the those types.
