### ISSUE TITLE
UnmanagedType Specialization

### ISSUE THREAD

**Issue by Akeit0** [Cysharp/MemoryPack#216]
Proposal of UnmanagedType Specialization
```cs
[MemoryPackable]
[Serializable]
public partial class Data<T>where T:unmanaged
{
   [MemoryPackUnmanaged]
    public T Value { get; protected set; } = default;
}
```
Then serializer use `ReadUnmanaged/WriteUnmanaged`.
Source generator can know whether generic T is unmanaged by ITypeSymbol.IsUnmanagedType.

**Comment by hadashiA** [comment]
Thanks for the suggestion.
For  the benefits, there seem to be a lot of difficulties.
- The default LayoutKind for class seems to be different from struct.
- Also, MemoryPack provides higher version compatibility for classes than structs.

**Comment by Akeit0** [comment]
Sorry, using ReadUnmanaged/WriteUnmanaged for unmanaged types seems to be already implemented.
However, SourceGenerator in [here](https://github.com/Cysharp/MemoryPack.git?path=src/MemoryPack.Unity/Assets/Plugins/MemoryPack) does not seem to have been updated.
