### ISSUE TITLE
Question: Does MemoryPackStreamingSerializer.DeserializeAsync function works like "lazy load"?

### ISSUE THREAD

**Issue by muhammetozeski** [Cysharp/MemoryPack#217]
Hi. Does MemoryPackStreamingSerializer.DeserializeAsync function works like "lazy load"? Namely, If I get a data from disk using DeserializeAsync by passing it a fileStream then do a foreach loop, does every iteration get values from disk one by one with a lazy load? or does this function load entire file to ram at once?

**Comment by neuecc** [comment]
バッファウィンドウだけを取得しながらループするため、データが大きい場合は遅延ロードになります。

**Comment by neuecc** [comment]
Sorry for answer in Japanese.
Translated:
To loop while only fetching the buffer window, it will result in delayed loading when the data is large.
