### ISSUE TITLE
MemoryPack.Generator.Roslyn3.dll is seems to be old

### ISSUE THREAD

**Issue by Angeart** [Cysharp/MemoryPack#219]
Hi, I installed MemoryPack via git URL into Unity, but [MemoryPack.Generator.Roslyn3.dll](https://github.com/Cysharp/MemoryPack/blob/1.10.0/src/MemoryPack.Unity/Assets/Plugins/MemoryPack/Runtime/MemoryPack.Generator/MemoryPack.Generator.Roslyn3.dll) is seems to be old (Probably that as is 1.9.11).

**Comment by hadashiA** [comment]
Hello. Thank you for your report.

MemoryPack's Unity support will be changed to dll distribution via NuGetForUnity instead of source code packages.
Therefore, please wait for the next release, as this issue is expected to be resolved.
