### ISSUE TITLE
MemoryPack does not work in LinqPad

### ISSUE THREAD

**Issue by VictorioBerra** [Cysharp/MemoryPack#220]
> MemoryPackSerializationException: UserQuery+Person is not registered in this provider.

![image](https://github.com/Cysharp/MemoryPack/assets/2934507/dd57f487-4f5f-4589-9dff-8e9319f86459)

**Comment by filzrev** [comment]
Currently LINQPad  don't supports `Source Generator`.
https://forum.linqpad.net/discussion/2396/source-generator-support

It's need to separately build DLLs  that contains MemoryPack's model class.

**Comment by hadashiA** [comment]
> Currently LINQPad don't supports Source Generator.
> https://forum.linqpad.net/discussion/2396/source-generator-support

Thanks for the explanation. Apparently it is not a MemoryPack repo issue.
