### ISSUE TITLE
MemoryPack not fully compatible with Visual Studio "Find references"

### ISSUE THREAD

**Issue by roland7685** [Cysharp/MemoryPack#228]
MemoryPack is a very useful tool, but it is currently not fully compatible with the **"Find references"** in Visual studio.

About  "Find references" in Visual studio
https://learn.microsoft.com/en-us/visualstudio/ide/finding-references

You can see the screenshot, if you use MemoryPack, and then use **"Find references"** function, Visual studio will display some useless information from the **source generator** and there is no button to filter this content. 

When you use more classes, there will be **hundreds or thousands of duplicate content**, making it difficult to find what you want to look up. This information may be useful, but most of the time we don't use it.

![001](https://github.com/Cysharp/MemoryPack/assets/160230789/4b9f55dc-4022-43f7-b42d-93fb9e24e31c)

**Comment by neuecc** [comment]
I agree, but this seems to be a problem with Source Generator in general, so I would like to see some kind of solution on the Visual Studio side.
Any additional information would be appreciated.

**Comment by roland7685** [comment]
System.Text.Json is a very commonly used class library, and it also use  Source Generator to create the dynamic code, but it seems that this problem does not occur. It seems that System.Text.Json has special processing.

https://learn.microsoft.com/en-us/dotnet/api/system.text.json
