### ISSUE TITLE
Make ContentType a static const string

### ISSUE THREAD

**Issue by burnchar** [Cysharp/MemoryPack#229]
The MemoryPack WebAPI InputFormatter and OutputFormatters have a private const specifying the ContentType:

`const string ContentType = "application/x-memorypack";`

This is useful but not usable. For example, if I write a WebAPI that is meant to only output MemoryPack format, I would add this attribute:
`[Produces(MemoryPackInputFormatter.ContentType)]`
However, this does not work because the string is private and non-static, so I need to duplicate the constant:

[Produces("application/x-memorypack")]

**Comment by hadashiA** [comment]
I agree with your point.
At #239, We added MemoryPack.AspNetCoreMvcFormatter.MediaTypeHeaderValues .
Please check it out.
