### ISSUE TITLE
Support for serializing to Spans

### ISSUE THREAD

**Issue by NickStrupat** [Cysharp/MemoryPack#23]
I propose new overloads for `Serialize` and `Deserialize` which operate on a `Span<Byte>` and `ReadOnlySpan<T>`, respectively.

Additionally, a new method would be required which returns the calculated size of the serialized object. Something like `GetSerializedByteLength`.

Together, it would enable zero-allocation serialization on the stack like this:

```csharp
const int maxStackAllocSize = 4096;
var length = MemoryPackSerializer.GetSerializedByteLength(v);
Span<byte> buf = length <= maxStackAllocSize ? stackalloc Byte[length] : new Byte[length];
MemoryPackSerializer.Serialize(v, buf);
var val = MemoryPackSerializer.Deserialize<Person>(bin, buf);
```

**Comment by neuecc** [comment]
If zero-allocation is the goal, how about the following approach?

```csharp
[ThreadStatic]
static ArrayBufferWriter<byte>? threadStaticBufferWriter;

public void Do<T>(in T? value)
{
    var bufferWriter = threadStaticBufferWriter;
    if (bufferWriter == null)
    {
        bufferWriter = threadStaticBufferWriter = new ArrayBufferWriter<byte>();
    }
    else
    {
        bufferWriter.Clear();
    }

    MemoryPackSerializer.Serialize(bufferWriter, value);

    var span = bufferWriter.WrittenSpan;
    // do anything...
}
```

Something like GetSerializedByteLength does not work very well.
The above approach is better from a performance standpoint.
