### ISSUE TITLE
.NET 8 class with primary constructors not supported

### ISSUE THREAD

**Issue by burnchar** [Cysharp/MemoryPack#230]
.NET 8 class with primary constructors not supported

```
// Records with primary constructors work:
[MemoryPackable]
public partial record MyClass(int MyInt);
```

```
// Class primary constructors fail
// MemoryPackable object 'MyClass' constructor's parameter 'MyInt' must match a serialized member name(case-insensitive)
[MemoryPackable]
public partial class MyClass(int MyInt);
```

Thank you for your amazing work on the world's fastest serializer!

**Comment by hadashiA** [comment]
Check the target members in the [README](https://github.com/Cysharp/MemoryPack#define-memorypackable-class--struct--record--record-struct).

Unlike record, parameter of the Primary constructor is not a public member.

For example, you can target the following

```cs
[MemoryPackable]
public partial class MyClass(int myInt)
{
    public int MyInt => myInt;
}
````

**Comment by burnchar** [comment]
My mistake, thank you for your reply.
