### ISSUE TITLE
Support types that aren't known at compile time

### ISSUE THREAD

**Issue by burnchar** [Cysharp/MemoryPack#236]
What are the chances that MemoryPack can support dynamic types? For example, we use applications that allow the user to request only the necessary columns from a database or other source, so the columns are not known until the query executes.

Dapper does an excellent job of putting this into a Dynamic, which can then be serialized to JSON or CSV or other formats (We do not use the Dynamic directly).

For mixed applications which use both concrete objects and dynamic ones, we can't consistently support MemoryPack. Can MemoryPack handle dynamic objects, even if it comes at a performance cost?

**Comment by neuecc** [comment]
No.
Because it is based on Source Generator, it cannot dynamically generate types.
Does not support completely type-less serialization/deserialization.

**Comment by burnchar** [comment]
Thank you for educating me.
