### ISSUE TITLE
Allow snake_case for constructor arguments

### ISSUE THREAD

**Issue by Joy-less** [Cysharp/MemoryPack#240]
Currently, if you have the following:
```cs
[MemoryPackable]
public partial class TestMessage {
    public readonly string ExampleText;

    public TestMessage(string example_text) {
        ExampleText = example_text;
    }
}
```
You get: `MEMPACK006: The MemoryPackable object 'TestMessage' constructor's parameter 'example_text' must match a serialized member name(case-insensitive)`

It works if you use `PascalCase` or `lowerCamelCase` or even `flatcase`, but not `snake_case`.
This could be resolved by ignoring all underscores between other characters (e.g. `_red_cat` treated as `_redcat`).

**Comment by neuecc** [comment]
Is there a strong reason why you want to use snake_case?
Generally it is not recommended.

**Comment by Joy-less** [comment]
> Is there a strong reason why you want to use snake_case?
> Generally it is not recommended.

There are many different coding styles. Snake case is common in Ruby, and it works in Newtonsoft.Json.

**Comment by hadashiA** [comment]
In the case of JSON, the key is a string, so JSON itself may be a snake_case expression; in the case of MemoryPack, it's only C# to C#, so other languages and such don't really matter I think.

Maybe you want to convert JSON -> C# -> MemoryPack. But even in that case, it seems to me that deserializing the JSON in snake_case to C# in camelCase would solve the problem.

If we support snake_case, we may need to support everything, including kebab cases. This would be complicated. We have decided to not to implemented it.

If you can point us to an important use case, we would welcome it. Thanks.

**Comment by Joy-less** [comment]
@hadashiA I think this issue should not have been closed. Constructors already support variables starting with an underscore, so the PR only extends the functionality by ignoring underscores completely. I use `snake_case` in constructors to differentiate from fields as a matter of preference. As for kebab case, C# identifiers don't support kebab case. I don't see a reason to reject the PR.

**Comment by neuecc** [comment]
Using `snake_case` in constructors is not common practice.
There is no need to add extra support just for that naming convention.
