### ISSUE TITLE
Model versioning compatibility

### ISSUE THREAD

**Issue by robertmircea** [Cysharp/MemoryPack#246]
If I have the following class dependencies:

```cs
[MemoryPackable(SerializeLayout.Explicit)]
public sealed partial record OperatorInfo(
 [property:MemoryPackOrder(0)] string Id,
 [property:MemoryPackOrder(1)] string OperatorName);

[MemoryPackable(SerializeLayout.Explicit)]
public partial record AuditEvent
{
    [MemoryPackOrder(0)]
    public OperatorInfo Oper {get; init;}
    [MemoryPackOrder(1)]
    public string MachineName { get; init; }

}
```

Is adding a new field to class `OperatorInfo` considered a breaking change for an existing consumer app?  For example, `OperatorInfo` gains field `Age` in v2:

```cs
[MemoryPackable(SerializeLayout.Explicit)]
public sealed partial record OperatorInfo(
 [property:MemoryPackOrder(0)] string Id,
 [property:MemoryPackOrder(1)] string OperatorName ,
 [property:MemoryPackOrder(2)] int Age);
```

More specifically: can an existing (not-upgraded with v2 OperatorInfo)  consumer app continue deserializing `AuditEvent` classes with both old and new `OperatorInfo` versions?

**Comment by hadashiA** [comment]
> can an existing (not-upgraded with v2 OperatorInfo) consumer app continue deserializing AuditEvent classes with both old and new OperatorInfo versions?

Unfortunately, your sample type definitions are not compatible with this.

However, specifying `GenerateType.VersionTolerant` will make the binary more backward compatible and allow your deserialization on older clients.

See the version tolerant section for more information.
https://github.com/Cysharp/MemoryPack?tab=readme-ov-file#version-tolerant


NOTE:
The number of members is written in the header of the MemoryPack binary.

By default,
1. If the  count  in the header of the binary is greater than the C# type definition, deserialization will fail.
2. If the count in the header of the binary is less than the C# type definition, deserialization will probably succeed. The missing parts are written with default values on a best-effort basis.

GenerateType.VersionTolerant support the case of 1.
