### ISSUE TITLE
CS0103 issue when upgrade project from NET6.0 to NET8.0

### ISSUE THREAD

**Issue by alexluozf** [Cysharp/MemoryPack#250]
Hello,

I upgraded my project from NET 6.0 to NET 8.0 and updated MemoryPack from Ver. 1.10 to Ver. 1.20.1.
My project compiled OK under NET 6.0 and MemoryPack Ver.1.10, but failure under NET8.0 and MemoryPack Ver.1.20.1.
IDE: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.3
Error code: CS0103
Description: The name 'EnFilterToken' does not exist in the current context. E:\Projects\Presence-Tech Projects\WindowsUITestApp\DBContext\MemoryPack.Generator\MemoryPack.Generator.MemoryPackGenerator\DBContext.DepartmentsInstance.MemoryPackFormatter.g.cs	235

![图像 001](https://github.com/Cysharp/MemoryPack/assets/62095636/97f5c007-84c5-44b6-8c4b-56dcf3f677d6)
![图像 002](https://github.com/Cysharp/MemoryPack/assets/62095636/eec14550-a8cd-4f91-8fd0-8acf69f7cbdf)

Please help to study.
Thanks a lot.
Alex Luo

**Comment by hadashiA** [comment]
Thanks for your report.
Can you provide us with the minimum code to reproduce the problem?

**Comment by hadashiA** [comment]
Probably the same problem as #251.

**Comment by alexluozf** [comment]
Thanks hadashiA, 
I have temporarily solved the problem by adding a namespace before the enumeration type.
![图像 005](https://github.com/Cysharp/MemoryPack/assets/62095636/77193b77-a314-483b-8cf3-7c09ba4c5f8f)
