### ISSUE TITLE
Something change with decimal types?

### ISSUE THREAD

**Issue by DevAlphaFox** [Cysharp/MemoryPack#255]
This worked fine  in v1.10, but v1.20.2 throws the following error: "CS0664: Literal of type double cannot be implicitly converted to type 'decimal'; use an 'M' suffix to create a literal of this type." It works if I remove the default parameter value or change myValue to a double.

	[MemoryPackable]
	public partial record TestClass {

		public decimal MyValue { get; set; }

		public TestClass(decimal myValue = 0.00m) {
			MyValue = myValue;
		}

	}

**Comment by DevAlphaFox** [comment]
Just to clarify, the error occurs during the build. v1.20.3 is also affected.

![MemoryPack (v1 20 3) - Build Error](https://github.com/Cysharp/MemoryPack/assets/154458155/54f649a6-952b-4c5e-87eb-a7cba11286b7)

**Comment by hadashiA** [comment]
Hello. Thanks for the report. And sorry. I had put a bug in #242.
We have just released the fixed version. I hope you will check it out.
