### ISSUE TITLE
Why are you dropping support for older Unity?

### ISSUE THREAD

**Issue by BaalEvan** [Cysharp/MemoryPack#256]
Hi!

Any reason why you are changing the working distribution workflow to Nuget and dropping support for older Unity?
Thanks to tags, most users can definitely stay on 1.10 if needed, but I'm curious why you decided to change that.

**Comment by hadashiA** [comment]
Thanks for the question. I will try to explain.

### Reasons for moving to NuGet

- MemoryPack was written using C# 11 and later features, but a downgraded version was needed to distribute the source code to Unity. This seemed to complicate maintenance a bit.
    - In the previous version, the source code was committed twice, once for Unity and once for dotnet. These synchronization errors have also occurred.
- Previous versions had API differences between MemoryPack built for Unity and MemoryPack from NuGet.
- MemoryPack depends on System.Runtime.CompilerServices.dll. For users, it was inconvenient to import this and resolve conflicts.

### Reasons for the increased Unity support version

- MemoryPack includes a SourceGenerator. For this to work with older Unity, the source generator for the Roslyn3 series and the code to be generated must work with C# 9. If this can be stopped, it will be easier to operate.
- NuGetForUnity did not have the ability to distribute multiple versions of SourceGenerator.
   - We hope this issue will be resolved here: https://github.com/GlitchEnzo/NuGetForUnity/pull/616.
- MemoryPack is also a progressive library with its own binary usage. We are also hopeful that most users will take advantage of the new Unity, as most probably are not conservative.


These are my views included.
However, Cysharp  is taking a similar direction for dotnet and Unity combined libraries such as R3 , ZLogger, etc.

**Comment by hadashiA** [comment]
Reason for moving to NuGet:.
- MemoryPack was written using C# 11 and later features, but a downgraded version was needed to distribute the source code to Unity. This seemed to complicate operations a bit.
    - In the previous version, the source code was committed twice, once for Unity and once for dotnet. These synchronization errors have also occurred.
    - The format of distributing dlls allows the code written for the new compiler to be diverted even if the line time is out of date.
- Previous versions had API differences between MemoryPack built for Unity and MemoryPack from NuGet.
- MemoryPack depends on System.Runtime.CompilerServices.dll, but already distributed this well to Unity projects
- The possibility of using NuGet libraries from Unity is expanding. In recent years, the NuGet libraries have been made AOT-safe by Source Generator.

Reasons for the increased Unity support version
- MemoryPack includes a SourceGenerator. For this to work with older Unity, the source generator for the Roslyn3 series and the code to be generated must work with C# 9. If this can be stopped, it will be easier to operate.
- NuGetForUnity did not have the ability to distribute multiple versions of SourceGenerator.
   - We expect this issue to be resolved here: https://github.com/GlitchEnzo/NuGetForUnity/pull/616.
- MemoryPack is also a progressive library with its own binary usage. We believe that most users are probably not conservative.

**Comment by Shaun-Fong** [comment]
After a day of trying to integrate latest version with my project, I decided to use version 1.10 😔that's a shame
