### ISSUE TITLE
Can we have ConvertToJson?

### ISSUE THREAD

**Issue by jonathanperis** [Cysharp/MemoryPack#269]
Hello!

Can we have ConvertToJson functionality on MemoryPack as we have on MessagePack? - https://github.com/MessagePack-CSharp/MessagePack-CSharp?tab=readme-ov-file#quick-start

**Comment by neuecc** [comment]
It is not possible.
This is because MessagePack retains some type information within its binary data, while MemoryPack does not include any at all.
