### ISSUE TITLE
Unity 2023.2.10f1 gives error in Generator

### ISSUE THREAD

**Issue by chmodseven** [Cysharp/MemoryPack#275]
Hi, I'm not sure if I'm being a donkey here and not installing it properly, but I have attempted to import the latest MemoryPack into a Unity 2023.2.10f1 project, to replace a previous version that came in a unitypackage with the current 1.21.0 via Nuget For Unity.

I get the following:
Assembly 'Assets/Packages/MemoryPack.Generator.1.21.0/analyzers/dotnet/cs/MemoryPack.Generator.dll' will not be loaded due to errors:
Unable to resolve reference 'Microsoft.CodeAnalysis'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Microsoft.CodeAnalysis.CSharp'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

I attempted to also nuget in that reference and it led to a whole rabbit warren of other errors.  So I created a temp project back on an older Unity 2022.3.20f1 install, and the latest MemoryPack installed just fine there over nuget, with no analyzer issues.

Is there some extra step I'm missing for Unity 2023+ or is it just not compatible there yet?  I can't fathom why 2022 would not get stuck in the CodeAnalysis dependency weeds while the other one fails.

**Comment by chmodseven** [comment]
Furthermore, in case it helps, when I reverted back to 1.10.0 using nuget for unity, I got the same error, however when I cleared out all of that and re-added it via the .unitypackage then all went back to normal.  So to summarise:

Unity 2022.3 - was able to install 1.21.0 via nuget for unity
Unity 2023.2 - was not able to install either 1.21.0 or 1.10.0 over nuget, but was ablr to revert to 1.10.0 unitypackage

**Comment by gambit-monkey** [comment]
I did pull over 1.10.0 from the project I am actually working on updating from Unity 2021 to 2023 and it did work. I was not however able to do https://github.com/Cysharp/MemoryPack.git?path=src/MemoryPack.Unity/Assets/MemoryPack.Unity#1.10.0 through Unity itself

**Comment by neuecc** [comment]
Thanks for the report.
I've been hearing about this problem a lot with ZLogger, which uses the same method,
https://github.com/Cysharp/ZLogger/issues/155
The problem seems to be that the Generator.dll is not labeled/run-time referenced for RoslynAnalyzer.
This should generate a meta that NuGetForUnity resolves at install time when installed with NuGetForUnity.

**Comment by xaroth8088** [comment]
FWIW, the same error occurs on Unity 6 Beta

**Comment by zhuxianzhiniko** [comment]
hi,all
Any temporary solution?
Thanks in advance

**Comment by neuecc** [comment]
maybe latest NuGetForUnity solves it.
https://github.com/GlitchEnzo/NuGetForUnity/releases/tag/v4.1.1

**Comment by patrickklug** [comment]
Having the same issue using NuGetForUnity v4.1.1 and Unity 2022.3.21f1 - cannot get it to compile.

**Comment by FrantisekHolubec** [comment]
Having the issue on NuGetForUnity v4.50 and Unity 6000.0.47
It compiles in editor but for batch build on CI/CD it fails for first editor run, after restart its ok... 
And yes I had the same problem with ZLogger, but I found I was not using it anymore so I just removed it.
But memory pack is essential for me.

**Comment by GoalLine01** [comment]
Still an issue in 2026 for Unity 2022.3.62f3, not sure why this thread is closed.

**Comment by rafay-pk** [comment]
- Here on Unity 6000.4, NugetForUnity 4.5.0, MemoryPack 1.21.4 (git and nuget), still getting errors Unable to resolve reference `Microsoft.CodeAnalysis` and `Microsoft.CodeAnalysis.CSharp`
- It says `Reference validation can be disabled in the Plugin Inspector`, however doing that gives 18 errors of `scripting_class_is_subclass_of was called with a NULL parameter. This will crash the game if it happens outside of the editor` and 1 error of `Unloading broken assembly Assets/Packages/MemoryPack.Generator.1.21.4/analyzers/dotnet/cs/MemoryPack.Generator.dll, this assembly can cause crashes in the runtime`
- I tried switching between API compatibility levels .NET framework and .NET standard 2.1 but errors persisted
- I tried moving the NugetPackages to Assets folder, deleting Unity Library folder and reopening the editor but errors persisted

**Comment by rafay-pk** [comment]
Explained the issue to an LLM (I just want fast serialization in my game) and it fixed the issue for me 
https://github.com/GlitchEnzo/NuGetForUnity/pull/754
