### ISSUE TITLE
Add pragma warning disable CS0618 to MemoryPackGenerator.Emitter.cs

### ISSUE THREAD

**Issue by crui3er** [Cysharp/MemoryPack#276]
C# compiler generates annoying warnings for generated classes like `Warning CS0618 : "DecoratedClass.ObsoleteProperty" is Obsolete` when decorated class has properties marked with ObsoleteAttribute.
It can be fixed by adding an extra disable warning directive to the list https://github.com/Cysharp/MemoryPack/blob/main/src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs#L80

**Comment by neuecc** [comment]
You're right. I think we should add it.
