### ISSUE TITLE
Any hope for supporting netstandard2.0?

### ISSUE THREAD

**Issue by TheXenocide** [Cysharp/MemoryPack#284]
I tried to look around other issues and it seems like newer language features are being used which made targeting other runtimes difficult, but I'm not sure which language features. Is there any chance of getting netstandard2.0 support? Maybe by using something like [PolySharp](https://github.com/Sergio0694/PolySharp) to polyfill the missing features so you can use C# 12 while still targeting netstandard2.0? 

We have an enterprise solution that is stuck using an older version of protobuf-net because they've removed support for polymorphism and the performance of this package looks very promising, but for now there's still .NET Framework 4.8 components that need to serialize and deserialize the same data that the newer .NET stuff does.

**Comment by neuecc** [comment]
It's probably possible, but it would require a significant amount of effort and add maintenance costs for future upkeep.
Since there doesn't seem to be much demand for it, I'm not currently considering adding it.
