### ISSUE TITLE
How do I use MemoryPack inside a source generator?

### ISSUE THREAD

**Issue by vertexfox** [Cysharp/MemoryPack#286]
I just want to atuomatically create classes with the [MemoryPackable] attribute. Example code:
```C#
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis;
using System.Text;


[Generator]
public class ExampleSourceGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        System.Console.WriteLine(System.DateTime.Now.ToString());


        var sourceBuilder = new StringBuilder(
        @"
            using System;
            using UnityEngine;
            using MemoryPack;

            [MemoryPackable]
            public partial class TestClass
            {
                public int TestInt { get; set; }
                public string TestString { get; set; }
            }
            
            ");

        context.AddSource("exampleSourceGenerator", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    public void Initialize(GeneratorInitializationContext context) { }
}



```

and it will throw the following errors in Unity:
`exampleSourceGenerator.cs(4,19): error CS0246: The type or namespace name 'MemoryPack' could not be found (are you missing a using directive or an assembly reference?)`

`exampleSourceGenerator.cs(9,18): error CS0246: The type or namespace name 'MemoryPackableAttribute' could not be found (are you missing a using directive or an assembly reference?)`

`exampleSourceGenerator.cs(9,18): error CS0246: The type or namespace name 'MemoryPackable' could not be found (are you missing a using directive or an assembly reference?)`

I already got the Nuget packages installed both in the Generator project
```
	<ItemGroup>
		<PackageReference Include="MemoryPack" Version="1.21.1" />
		<PackageReference Include="MemoryPack.Core" Version="1.21.1" />
		<PackageReference Include="MemoryPack.Generator" Version="1.21.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis" Version="3.8.0" />
	</ItemGroup>
```

and Unity.

Is there any way to use MemoryPack in a source generator? Based on the information I'm finding on the internet, it seems like source generators don't work with other source generators. Is there anything in missing? I assume I have to do something with MemoryPack.Generator instead?

**Comment by neuecc** [comment]
Source Generator can also output files.
For example
```csharp
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
```
Pre-generating in this way would be the easiest method for stable use.
