### ISSUE TITLE
Support for signalR

### ISSUE THREAD

**Issue by kaizendevsio** [Cysharp/MemoryPack#287]
Hi guys first thanks for another awesome library! 

We just like to know if there will be a signalR support just like message pack?

**Comment by neuecc** [comment]
SignalR's MessagePack is tightly coupled with the protocol and implementation, not just the serialization of the Body.
Therefore, it would be difficult to use anything other than the official implementation (JSON, MessagePack).

**Comment by kaizendevsio** [comment]
@neuecc Thanks! so would it be better to say that I should raise this instead to aspnet team?

**Comment by neuecc** [comment]
It would likely be wasteful to ask for ASP.NET to support MemoryPack.
However, I agree with the proposal of allowing customization of the serializer for the body in the Binary Protocol (based on MessagePack).
This would enable fulfilling requests such as using protobuf for the body serialization.
