### ISSUE TITLE
Is it possible to utilise MemoryPack to compare serialized data of the same type?

### ISSUE THREAD

**Issue by byte-arcane** [Cysharp/MemoryPack#298]
e.g. I serialize two objects of type T, and the binary stream is different. 

Is there a way to identify which properties are different? output could be series of type "paths" e.g. "object.someProperty.someArray[2]"

I don't suppose there is, but are there any existing APIs in MemoryPack that would allow to implement this functionality in a nice, clean way? Obviously I only care about the serializable properties. I think it could be quite useful.

**Comment by neuecc** [comment]
can not.
