### ISSUE TITLE
[Question] Why are unions only supported for class and not struct, and is there a work around?

### ISSUE THREAD

**Issue by Karatakos** [Cysharp/MemoryPack#299]
My data is encapsulated via components attached to entities (ECS). For client/server communication i need to serialize a set of _struct_ components for any given entity so i can compress and send over the wire. 

Since each component is a unique type, and Memorypack does not output type information, I wanted to solve by using a union on some interface my struct components could implement, but noticed the compiler error noting class only support for unions.

So: 

1. Is it possible to get union working with structs? Assuming not, then:
2. Is there a recommended workaround or alternative for this use case?

Many thanks.

**Comment by neuecc** [comment]
As can be seen from the proposal for struct unions in C#, it is currently not possible to handle them as natural types.
https://github.com/dotnet/csharplang/blob/18a527bcc1f0bdaf542d8b9a189c50068615b439/proposals/TypeUnions.md
By preparing custom types and formatters, it should be possible to process them in places where special performance is a concern.
