### ISSUE TITLE
Unity console log file links do not navigate to generated files

### ISSUE THREAD

**Issue by jarrodspurrier** [Cysharp/MemoryPack#323]
When using with Unity, the blue file link found in the Console doesn't open generated files in your configured IDE. I think it would improve usability and productivity if this feature worked as I could more easily navigate to and debug generated formatters. Is there a way to open/view/debug generated providers in Rider for instance? I'd love to be able to use them as a reference point for learning how to write my own custom formatters.
![image](https://github.com/user-attachments/assets/a51e2044-4528-423a-a4f3-4586d3b47aee)

**Comment by neuecc** [comment]
The actual file for the generated code only exists in the memory of the compilation process, so it will be difficult to open.
