### ISSUE TITLE
DynamicUnionFormatter syntax gives compile error

### ISSUE THREAD

**Issue by SerratedSharp** [Cysharp/MemoryPack#329]
This syntax from readme gives compile error `Argument 1: cannot convert from '(int, System.Type)[]' to '(ushort Tag, System.Type Type)'`:

```
var formatter = new DynamicUnionFormatter<IFooBarBaz>(new[]
{
    (0, typeof(Foo)),
    (1, typeof(Bar)),
    (2, typeof(Baz))
});
```

Changing to this syntax to leverage `params` instead of using a type inferred array resolves error:

```
var formatter = new DynamicUnionFormatter<IFooBarBaz>(
    (0, typeof(Foo)),
    (1, typeof(Bar)),
    (2, typeof(Baz))
);
```

The problem is the array syntax allows the type to be inferred, and it infers int instead of ushort.  You could also resolve with:
```
var formatter = new DynamicUnionFormatter<IFooBarBaz>(
   new[] {
    ((ushort)0, typeof(Foo)),
    ((ushort)1, typeof(Bar)),
    ((ushort)2, typeof(Baz))
});
```

Or explicitly declaring the array type:
```
var formatter = new DynamicUnionFormatter<IFooBarBaz>(
   new  (ushort, Type)[] {
    (0, typeof(Foo)),
    (1, typeof(Bar)),
    (2, typeof(Baz))
});
```

**Comment by neuecc** [comment]
thanks, I've modified in ReadMe(use params)
