### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by matoomx** [Cysharp/MemoryPack#51]
Hi and thanks for your work to provide super-fast serializers for c#.
When testing a migration from MessagePack to MemoryPack I think I stumbled upon a possible bug when serializing a int into IBufferWriter.

I think the trouble is on row 86 in MemoryPackSerializer.Serialize.cs where Advance(span.Length) is called but the span.Length can be much larger than the serialized data since its legal for IBufferWriter<byte>.GetSpan() on row 84 to return a larger span than requested.  
 
Hope I'm describing the issue I am seeing well enough /Mattias

**Comment by neuecc** [comment]
Thanks!
Thank you for the detailed information, it is helpful.
I've released `1.7.3`, it includes this fix.
