### ISSUE TITLE
Add a new constructor for MemoryPackUnionAttribute by using FullName,Assembly info of a type in addition to typeof(Type)

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#57]
Suggested new constructor:  [MemoryPackUnion(0, "MyNamespace.MyType, MyAssemblyName")]

this is useful when the implementing type is not in the same assembly with the Interface, which is usually isolated from its implementation and MemoryPackUnionAttribute may not possibly make a reference to it by typeof() operator.

this is a similar measure in:
 [Editor("MyNamespace.ByteArrayEditor, MyAssemblyName", "System.Drawing.Design.UITypeEditor, System.Windows.Forms")]

**Comment by neuecc** [comment]
It is undesirable to apply dependencies from the inside to the outside with strings.
#17 proposal would solve the problem, and I think it would be better to implement it.

**Comment by xiaoyuvax** [comment]
[MemoryPackFormatter] is not a bad idea! late-binding union info is more practical and flexible.
just waiting for new NuGet package release with this update, and my project can't work without it.
