### ISSUE TITLE
Typescript casing

### ISSUE THREAD

**Issue by matengo** [Cysharp/MemoryPack#63]
I have testet out the library, it's fantastic :)
Is there any way to control the casing of generated typescript models?

**Comment by neuecc** [comment]
Currently no but I can add new feature.
What cases would you like?

**Comment by matengo** [comment]
It would be good if it would be able to keep the casing as of the original class, so that the generated typescript models have the same casing as the original C# classes.

In json options for asp.net core input/output formatters you can control it by setting:

In Newtonsoft.Json:
options.SerializerSettings.ContractResolver = new DefaultContractResolver();

In System.Text.Json
options.JsonSerializerOptions.PropertyNamingPolicy = null;

(When we then generate typescript clients from the swagger spec we then get the same casing of the typescript models, as of the C# classes.)

**Comment by neuecc** [comment]
I've added `MemoryPackGenerator_TypeScriptConvertPropertyName` option, it includes in next release.

**Comment by matengo** [comment]
Wow, very nice!!

**Comment by neuecc** [comment]
released `1.8.7`.
