### ISSUE TITLE
 [MemoryPackUnion(ushort tag, Type type )]  the "tag" parameter is kinda excessive,  can it be removed or optional?

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#64]
Suggest: `MemoryPackUnion(Type type, ushort? tag=null )]  `
if null, code generator assign the tag for each type accordingly.

I don't know why must serve this tag parameter to the the MemoryPackUnion attribute, it's boring to assign a sequence of unfriendly numbers which will not be used later to a pile of classes.

**Comment by neuecc** [comment]
completely no, set explicitly.

**Comment by xiaoyuvax** [comment]
I don't care the sequence of the type registered, and the numebrs r not gonna be reused, why can't the generator just fill it automatically? 
omg, what if i have hundreds classes to register?

**Comment by neuecc** [comment]
If you have hundreds of them, you can just fill in the sequential numbers if they're auto-generated. If not, you can just fill them.
For Union tags, please CARE, for Version Tolerant.

**Comment by xiaoyuvax** [comment]
one more question: does the tag numbers decide the deserialization priorities of types to be instantiated?
i.e. i can use the  tag to optimize which type to be used first?

**Comment by xiaoyuvax** [comment]
ok, i got it, seems Version Toloerance also requires carefully handle of these numbers, in another word, the orders, right?
but declare orders of the [MemoryPackUnion] already implies the orders for serialization, why not just use the declare order instead of the tags, even for Version Tolerance?

is 
```
[MemoryPackUnion(0,Type1)]
[MemoryPackUnion(1,Type2)]
[MemoryPackUnion(2,Type3)]
```

equal to 

```
[MemoryPackUnion(1,Type1)]
[MemoryPackUnion(3,Type2)]
[MemoryPackUnion(5,Type3)]
```
?

**Comment by neuecc** [comment]
What do you do when you delete type.
Basically, I prefer to be explicit, automatically member order is a special exception for me.

**Comment by xiaoyuvax** [comment]
The order is not automatically random, u can INFER the order from the [MemoryPackUnion] declaration?
and eliminate a parameter as to make coding easier.

**Comment by xiaoyuvax** [comment]
or [MemoryPackUnion(IList<Type>)]  is better?
