### ISSUE TITLE
MEMPACK019	when compiling a subclass inherited from Dictionary or ConcurrentDictionary.

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#65]
MEMPACK019	The MemoryPackable object 'ConfigDictionary' member 'Comparer' type 'global::System.Collections.Generic.IEqualityComparer<string>' is not MemoryPackable. Annotate [MemoryPackable] to 'global::System.Collections.Generic.IEqualityComparer<string>' or if external type that can serialize, annotate `[MemoryPackAllowSerialize]` to member	....

"Comparer" seems a protected member of Dictionary or ConcurrentDictionary.

```
[MemoryPackable]
    public partial class ConfigDictionary<T> : Dictionary<string, T>
 {
}
```

**Comment by neuecc** [comment]
use `[MemoryPackable(GenerateType.Collection)]`.

**Comment by xiaoyuvax** [comment]
sovled! thx, should have read the document.
A similar question: why doesn't the code generator just infer the collection type?

**Comment by neuecc** [comment]
>  why doesn't the code generator just infer the collection type?

This is what I thought when I responded!
Eventually, I may change to infer type.

**Comment by xiaoyuvax** [comment]
LOL
