### ISSUE TITLE
Why allocating if value is unmanaged?

### ISSUE THREAD

**Issue by sebas77** [Cysharp/MemoryPack#66]
Hi, about this code:

```  
public static byte[] Serialize<T>(in T? value, MemoryPackSerializerOptions? options = default)
    {
        if (!RuntimeHelpers.IsReferenceOrContainsReferences<T>())
        {
            var array = AllocateUninitializedArray<byte>(Unsafe.SizeOf<T>());
            Unsafe.WriteUnaligned(ref GetArrayDataReference(array), value);
            return array;
        }
```
        
I am not sure why ReusableLinkedArrayBufferWriter is not used for this case too. wouldn't this mean a certain allocation?

**Comment by neuecc** [comment]
Return type is `byte[]`.
If you use the ReusableLinkedArrayBufferWriter, It would still do a ToArray at the end.

**Comment by sebas77** [comment]
I actually noticed that and in fact I was wondering if there is way to allow me to pass a Span<byte> from outside as target buffer (for example in my case I can use stack alloc as target buffer for the serialization)

**Comment by neuecc** [comment]
You can use `IBufferWriter<byte>` overload, it can control buffer pooling.
