### ISSUE TITLE
Can an extra interface representing the abstract for all MemoryPackable types be added ?

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#69]
CASE: I need to serialize any MemoryPackable objects using an array or colleciton but seems not possible, cos the most abstract interface IMemoryPackFormatterRegister has a static member, which can not be used as a type parameter.

I think a more abstract interface without static member could solve this problem, couldn't it?

SUGGEST:
```
namespace MemoryPack
{
    public interface IMemoryPackFormatterRegister: IMemoryPackObject
    {
        static void RegisterFormatter();
    }


    public interface IMemoryPackObject {} 

}



```

lexically, i prefer the name IMemoryPackable, but it was already used.  
A more reasonable hierachy might be IMemoryPackObject: IMemoryPackFormatterRegister : IMemoryPackable

**Comment by neuecc** [comment]
I don't understand what you say...
Before making suggestions, please give specific code for the problem.

**Comment by xiaoyuvax** [comment]
it's not easy to express with codes, i'll try below:

my old code:

```
public class MyClass
{
object[] items;
}
```
I want to make it MemoryPackable, so i refactor it to:

```
[MemoryPackable]
public partial class MyClass
{
object[] items;                               <- i expect IMemoryPackableObject[] Items here, for object array seems can not be serialized 
                                                          by MemoryPack.
}
```

**Comment by neuecc** [comment]
To begin with, objects cannot be serialized.
This is because the type is not known at deserialization time.

**Comment by xiaoyuvax** [comment]
so i need a common type/interface for all MemoryPackable types, such as IMemoryPackableObject

**Comment by neuecc** [comment]
I don't know what the solution to that is.
If you want object's Formatter, you can define it?

**Comment by xiaoyuvax** [comment]
Solution1:  myself, to define a root level interface for all my types which is marked with [MemoryPackable] to inherit from, and use a formatter to reigster all these inheriting types under that interface.

Solution2:  MemoryPack adds a rootlevel interface inherited by the existing IMemoryPackFormatterRegister,  as i've suggested. Then i can serve that Interface directly as the type parameter as in  List<T>, Dictionary<T1,T2> ...  to allow the List or Dictionary accomodating elements of any MemoryPackable types.

**Comment by xiaoyuvax** [comment]
I have tested Solution 2 by reference MemoryPack source project in mine, after adding an extra interface, just to find i still need all extra formatters for all types.  for interfaces defined in MemoryPack r not MemoryPackables themselves, lol
So i take Solution 1.
