### ISSUE TITLE
[MemoryPackUnionFormatter] (net7.0) yields compiling error: CS8987 The ‘scoped’ modifier of parameter ‘value’ doesn’t match overridden or implemented member

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#71]
I have various Types defined in 3 libs, namely Model, Man, Config,  and these types are finally used in the lib: Server 
i.e. Server depends on Model, Man, Config, otherwise Man and Config depends on Model.  
And, All these Types inherits a single interface  `IMyMemoryPackable` defined in Model.

I wrote a MyMemoryPackableFormtter.cs in lib Server like this to register all these types:
```
[MemoryPackUnionFormatter(typeof(IMyMemoryPackable))]
    [MemoryPackUnion(0, typeof(Type1))]
    [MemoryPackUnion(1, typeof(Type2))]
    [MemoryPackUnion(2, typeof(Type3))]
    public partial class MyMemoryPackableFormatter
    {
    }
```

but compiler yields:
Server (net7.0) :  
compiling error: CS8987 The ‘scoped’ modifier of parameter ‘value’ doesn’t match overridden or implemented member

However,
if i split this `MyMemoryPackableFormatter`  into three separate Formatters(note all these formatters register for the same interface, namely `IMyMemoryPackable`) into three libs (no matter their names r the same or not), the compiler compiles OK and the program can launch, but the generated code seems only to use one Formatter to do serialize Job (other Types cannot be found ).

**Comment by neuecc** [comment]
Is the target framework the same for all projects?
MemoryPack is not compatible with netstandard2.1 and net7.

**Comment by xiaoyuvax** [comment]
All these libs are dual-targeted, and have passed compiling before MemoryPackUnionFormatter was introduced, that proves not possibly the case of incompatibility.

And please note the case in my descrption after "However,...",  in that case the program is successfully compiled, only throws expception on Type missing, as also proves no problem of incompatibility.

**Comment by neuecc** [comment]
Sorry, it's a bit tough to read, can you give me a reproduction repo?

**Comment by xiaoyuvax** [comment]
https://github.com/xiaoyuvax/MemoryPackUnionFormatterRepro.git

compile the Server project u'll see the error.

**Comment by xiaoyuvax** [comment]
i suddenly found it's possibly because of the LangVersion not compatible

**Comment by xiaoyuvax** [comment]
Confirmed: the server used LangVersion=9.0 , it is not qualified to compile , set it to 11.0, compile passed!
