### ISSUE TITLE
TypeScript generator does not generate serializers and enums

### ISSUE THREAD

**Issue by danfma** [Cysharp/MemoryPack#73]
I was impressed by how amazing this library is!! 
And, even more, after seeing that TypeScript would be supported.

## Bug description

I don't know yet if there is a problem with the latest versions, but it looks like the generator is not generating the runtime and dependent files.

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/101121/204094094-9de841b5-2276-43a7-b889-4b44c51c9b75.png">

## Expected behavior

* Runtime should be emitted;
* Dependent types should also be generated.

## Working version

Version 1.8.6 is working as expected.

**Comment by neuecc** [comment]
released at 1.8.9, thanks!
