### ISSUE TITLE
Feature proposal: Formatter Merging, to support assembly dependency architecture and assemblies loaded during runtime(such as plugin)

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#76]
AssemblyA: 
```
[MemoryPackUnionFormatter(typeof(IPlugin))]
 [MemoryPackUnion(0, typeof(Plugin1))]
 [MemoryPackUnion(1, typeof(Plugin2))]
 public partial class PluginFormatter
 { }
```
AssemblyB: 
 ```
[MemoryPackUnionFormatter(typeof(IPlugin))]
 [MemoryPackUnion(2, typeof(Plugin3))]
 [MemoryPackUnion(3, typeof(Plugin4))]
 public partial class PluginFormatter
 { }
```

Question: Is it possible to merge the MemoryPackUnionFormatters declared in different assemblies (like above) referencing the same interface with/without same class names? 
The underlying solution might be allowing formatters for each interface be registered more than once and merge the types into one type dictionary (together with their tags) or be search through a hierachy of dicitonaries.

This solves following issue:
1) MemoryPackUnionFormatter must be centralized in the final consumer libs, and cannot be distributed in different assemblies, if these libs r used by different programs, each program must write their own formatter (a lot of redundency work), why can not the type registration be done by each assembly on module basis and they merge to one when compiled, while programmers can negotiate tag segments for each assembly to avoid conflicts, like 1-10 for assembly one, 20-30 for another?

2) Unreferenced types(with known interface) declared in plugin assembly r not applicable for MemoryPack, cos they r not pre-registered in the host program, but what if their types come as compiled with MemoryPack with code already generated?

**Comment by neuecc** [comment]
How about this approach?
Introduce `DynamicUnionFormatter<T>`.

```csharp
var formatter = new DynamicUnionFormatter<IPlugin>(new[]
{
    (0, typeof(Plugin1)),
    (1, typeof(Plugin2)),
    (2, typeof(Plugin3)),
    (3, typeof(Plugin4))
});

MemoryPackFormatterProvider.Register(formatter);
```

**Comment by xiaoyuvax** [comment]
Do you mean?

AssemblyA:
```
var formatterA = new DynamicUnionFormatter<IPlugin>(new[]
{
    (0, typeof(Plugin1)),
    (1, typeof(Plugin2)),
    });

```

AssemblyB:
```
var formatterB = new DynamicUnionFormatter<IPlugin>(new[]
{
(2, typeof(Plugin3)),
    (3, typeof(Plugin4))
}

```
AssemblyC:
```
MemoryPackFormatterProvider.Register(formatterA);

**Comment by neuecc** [comment]
The idea is not combine Formatters.
DynamicUnionFormatter accepts `(ushort Tag, Type Type)[]`.
You can assemble it in code as you wish, either by Reflection or manually.

**Comment by neuecc** [comment]
For example, register all types dynamically.

```csharp
var pluginInheritedTypes = AppDomain.CurrentDomain.GetAssemblies()
    .SelectMany(x => x.GetTypes())
    .Where(x => typeof(IPlugin).IsAssignableFrom(x))
    .OrderBy(x => x.Name)
    .Select((type, tag) => ((ushort)tag, type))
    .ToArray();

var formatter = new DynamicUnionFormatter<IPlugin>(pluginInheritedTypes);
```

**Comment by xiaoyuvax** [comment]
I just want to know if the "formatter" in ur code above can be exposed by the plugin assembly to the host program and the host can register it later when the plugin is loaded. 

If so, i can then create such dynamic formatters in each assembly(no matter if it's plugin or not) and register them whenever  needed  in the consumer assembly.

**Comment by neuecc** [comment]
The Register of FormatterProvider can be overwritten, so you can just overwrite it when it is loaded.
If you want to assemble from each Formatter, just read it with GetAttribute.

**Comment by xiaoyuvax** [comment]
1) How would the DynamicFormatter behave if multiple formatters register for the same interface?
2) Is FormatterProvider.Register() static? 
3) Assemble from each formatter, and the GetAttribute, can u give a code example?  Declare isolatedly and Assemble-On-Demand is what i care most.
4) Can i Unregister?

**Comment by neuecc** [comment]
Overwritten by the latest.

**Comment by xiaoyuvax** [comment]
If i've registered for InterfaceA in host program when it's started, and then later when I loaded a plugin during the execution., which wants to register for InterfaceA too with its own types, what should i do to make all types work together (either registered earlier or later with the plugin) ?

**Comment by xiaoyuvax** [comment]
I bettered above code to get all MemoryPackableTypes for specified interface, but this method CANNOT get instantiated custom GENERIC TYPES, such as MyList<MyMemoryPackableType> (there are numerable combinations), such types need to register one by one manually and carefully avoid tag conflicts.
```
 public static (ushort, Type)[] GetAllMemoryPackableTypes<T>() => AppDomain.CurrentDomain.GetAssemblies()
                                            .SelectMany(asm =>
                                            {
                                                try { return asm.GetTypes(); }
                                                catch
                                                {
                                                    //in case of failure
                                                }
                                                return Array.Empty<Type>();
                                            })
            .Where(t => typeof(T).IsAssignableFrom(t) && t.GetCustomAttribute(typeof(MemoryPackableAttribute)) != null)
            .OrderBy(t => t.Name)
            .Select((t, tag) => ((ushort, Type))(tag, t))
            .ToArray();
```
