### ISSUE TITLE
__typeToTag.TryGetValue(value.GetType(), out var tag) cannot identify the same Type created in a plugin.

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#78]
if u have a type used in a plugin (i.e. dynamically loaded assembly) while registered with [MemoryPackUnionFormatter] in the host program, the following line in in the generated code seems unable to get the Type, even The type names are same.

`  if (__typeToTag.TryGetValue(value.GetType(), out var tag))`

this is possibly because the Type registered in `__typeToTag` is not the same object with `value.GetType()`, even though their FullNames and GUIDs r the same, for the former was instantiated at host launch, but the latter was instantiated when load the plugin.

is it better to use type GUID as Key?

**Comment by neuecc** [comment]
Try to make the Type unique.

**Comment by xiaoyuvax** [comment]
nah, can't u see the Type is Unique, but the references to the Type objects r not Unique, what can i do?

The problem with using reference as the Key for Dictionary is that it uses reference to determine if it matches, instead of compare Type itself.
