### ISSUE TITLE
Integration with MagicOnion

### ISSUE THREAD

**Issue by FoxTes** [Cysharp/MemoryPack#82]
Will there be integration with MagicOnion?
I would like to see an example in ASP Net with zero allocation for objects of a value type, for example structures.

**Comment by neuecc** [comment]
We're working MagicOnion v5, it has many changes and improvement.
Integration may also be included.
https://github.com/Cysharp/MagicOnion/pull/497

**Comment by FoxTes** [comment]
Tell me, will ASP be supported?
I really want to have sterilization with zero allocation.
