### ISSUE TITLE
How to mark up external objects (ie Unity Vector3, etc)

### ISSUE THREAD

**Issue by strich** [Cysharp/MemoryPack#83]
Hi,

This looks great and congrats on the new library. It's clear you've been using this library in Unity projects so I hope there is a simple answer here: If one uses Newtonsoft .NET JSON serializer in a Unity project you typically have to define some custom contracts to properly serialize various Unity structs and classes that are common to add to serialized data. For example an `AnimationCurve`. 
Does MemoryPack have a similar ability to mark up or write contracts for external C# structures that we cannot access?

**Comment by neuecc** [comment]
struct that includes no reference types(for example `Vector3`, `Keyframe`, `Rect`, `Bound`, etc) can serialize in default.
For other types, a custom wrapper must be created.
For example, AnimationCurve would look like this.

```csharp
// Keyframe: (float time, float inTangent, float outTangent, int tangentMode, int wightedMode, float inWeight, float outWeight)
[MemoryPackable]
public readonly partial struct SerializableAnimationCurve
{
    [MemoryPackIgnore]
    public readonly AnimationCurve AnimationCurve;

    [MemoryPackInclude]
    WrapMode preWrapMode => AnimationCurve.preWrapMode;
    [MemoryPackInclude]
    WrapMode postWrapMode => AnimationCurve.postWrapMode;
    [MemoryPackInclude]
    Keyframe[] keys => AnimationCurve.keys;

    [MemoryPackConstructor]
    SerializableAnimationCurve(WrapMode preWrapMode, WrapMode postWrapMode, Keyframe[] keys)
    {
        var curve = new AnimationCurve(keys);
        curve.preWrapMode = preWrapMode;
        curve.postWrapMode = postWrapMode;
        this.AnimationCurve = curve;
    }

    public SerializableAnimationCurve(AnimationCurve animationCurve)
    {
        this.AnimationCurve = animationCurve;
    }
}
```

As it is, I have to wrap it every time, which is inconvenient.
Let's create a custom formatter.

```csharp
public class AnimationCurveFormatter : MemoryPackFormatter<AnimationCurve>
{
    public override void Serialize(ref MemoryPackWriter writer, ref AnimationCurve value)
    {
        writer.WritePackable(new SerializableAnimationCurve(value));
    }

    public override void Deserialize(ref MemoryPackReader reader, ref AnimationCurve value)
    {
        var wrapped = reader.ReadPackable<SerializableAnimationCurve>();
        value = wrapped.AnimationCurve;
    }
}
```

and register in startup.

```csharp
MemoryPackFormatterProvider.Register<AnimationCurve>(new AnimationCurveFormatter());
```

**Comment by strich** [comment]
That looks acceptable to me, thanks! It appears you've done this before - It would be great to provide an extension repo with various Unity structures support too. Would be happy to contribute to that when we look into migrating to MemoryPack.
