### ISSUE TITLE
How does this compare to System.Text.Json.Serialization

### ISSUE THREAD

**Issue by 107295472** [Cysharp/MemoryPack#85]
System.Text.Json.Serialization,Newtonsoft.Json

**Comment by 107295472** [comment]
System.Text.Json.Serialization,Newtonsoft.Json

**Comment by neuecc** [comment]
?
top graph is compare with System.Text.Json.Serialization.
Newtonsoft.Json is too slow so not included in the graph.

**Comment by 107295472** [comment]
![V~~AVCI)5@3~V5GL`RK4__9](https://user-images.githubusercontent.com/6436116/205254422-026124b9-7985-4779-a41a-70c4756611eb.png)

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/205254544-91a11386-a321-4dc2-8514-aadfbe67bc7b.png)

**Comment by 107295472** [comment]
I tested that Newtonsoft.Json is not slow

**Comment by neuecc** [comment]
maybe Student type not marked `[MemoryPackable]`, see ReadMe.

In others' tests, JsonNet is in the Slow group.
https://aloiskraus.wordpress.com/2022/11/23/net-serialization-roundup-2022/

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/205261003-463ec770-2f5d-4dee-8b05-f6bc3fafe98a.png)
It doesn't work with your demo, does it not support .net6.0?

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/205261137-49284cff-ed46-4344-85c5-4fa85aca01a6.png)

**Comment by neuecc** [comment]
supported but is your VisualStudio version?

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/205261233-b60548e8-aa4b-44a5-bb70-467e5950de44.png)

**Comment by 107295472** [comment]
Microsoft Visual Studio Community 2022 (64 位) - Current
17.3.4

**Comment by neuecc** [comment]
Please show full code to reproduce easily, Program.cs and .csproj

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/205261935-d08bfd8d-5c7d-4d42-bd97-f15b58769e34.png)
![image](https://user-images.githubusercontent.com/6436116/205261956-8766db11-f584-48f9-8014-8967f3606212.png)
![image](https://user-images.githubusercontent.com/6436116/205262006-dfdf957a-2287-4f33-9618-602e47259af9.png)
![image](https://user-images.githubusercontent.com/6436116/205262027-7bf01d35-9536-44d9-9934-c05643bb653b.png)

**Comment by neuecc** [comment]
why image?
I can't paste code...

**Comment by neuecc** [comment]
In my environment, it works.

![image](https://user-images.githubusercontent.com/46207/205263850-75ceb8b9-0f6d-45d5-b0ac-f3d31c999fb7.png)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.8.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>
```

**Comment by 107295472** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.8.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>

**Comment by 107295472** [comment]
`using MemoryPack;
using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ConsoleApp1
{
    [MemoryPackable]
    //[GenerateTypeScript]
    public partial class Student
    {
        public int Age { get; set; }
        public string? Name { get; set; }
    }
    [MemoryPackable]
    public partial class Overwrite
    {
        public int MyProperty1 { get; set; }
        public int MyProperty2 { get; set; }
        public String? MyProperty3 { get; set; }
        public string? MyProperty4 { get; set; }
    }
    public class Teacher
    {
        public int Id { get; set; }
        public string? TeacherName { get; set; }
        public DateTime Birthday { get; set; }
        public string? Address { get; set; }
    }

    //[JsonSourceGenerationOptions(WriteIndented = true)]
    //[JsonSerializable(typeof(Student))]
    //[JsonSerializable(typeof(Teacher))]
    //internal partial class SourceGenerationContext : JsonSerializerContext
    //{

    //}

    public class Program
    {
        public static void Main(string[] args)
        {

            //Stopwatch stopwatch1 = new Stopwatch();
            //stopwatch1.Start();
            //foreach (var index in Enumerable.Range(0, 10000))
            //{
            //    JsonSerializer.Serialize(student, new JsonSerializerOptions()
            //    {
            //        WriteIndented = true,
            //        PropertyNameCaseInsensitive = true
            //    });
            //}
            //stopwatch1.Stop();
            //Console.WriteLine($"原始的序列化时间:{stopwatch1.ElapsedMilliseconds}");

            //Stopwatch stopwatch2 = new Stopwatch();
            //stopwatch2.Start();
            //foreach (var index in Enumerable.Range(0, 10000))
            //{
            //    JsonSerializer.Serialize(student, SourceGenerationContext.Default.Student);
            //}
            //stopwatch2.Stop();
            //Console.WriteLine($"源码生成器的序列化时间:{stopwatch2.ElapsedMilliseconds}");

            //Stopwatch stopwatch4 = new Stopwatch();
            //stopwatch4.Start();
            //foreach (var index in Enumerable.Range(0, 10000))
            //{
            //    Newtonsoft.Json.JsonConvert.SerializeObject(student);
            //}
            //stopwatch4.Stop();
            //Console.WriteLine($"Newtonsoft序列化时间:{stopwatch4.ElapsedMilliseconds}");

            Student student = new()
            {
                Age = 334,
                Name = "上海市浦东新区"
            };
            var write = new Overwrite()
            {
                MyProperty1 = 10,
                MyProperty2 = 20,
                MyProperty3 = "foo",
                MyProperty4 = "bar"
            };
            Stopwatch stopwatch3 = new();
            stopwatch3.Start();
            //foreach (var index in Enumerable.Range(0, 10000))
            //{
            //    MemoryPackSerializer.Serialize(student);
            //}
            var bin=MemoryPackSerializer.Serialize(write);
            stopwatch3.Stop();
            Console.WriteLine($"Memory的序列化时间:{stopwatch3.ElapsedMilliseconds}");


            Console.ReadKey();
        }
    }
}
`

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/205283951-ecbce96d-261d-481c-a4dd-4838c316997b.png)

**Comment by 107295472** [comment]
The machine at home is fine, is the version low?

**Comment by 107295472** [comment]
This speed is the same as SourceGenerationContext

**Comment by neuecc** [comment]
You code does not include warmup.
call twice maybe get different result.

![image](https://user-images.githubusercontent.com/46207/205285983-d6d8af48-3a4b-43c7-bffd-9cdd934ed28e.png)

**Comment by neuecc** [comment]
Maybe there is some minor version difference < visual studio.
At any rate, the latest is 17.4.0, so please use that.

**Comment by 107295472** [comment]
It's working
