### ISSUE TITLE
Document issue: DynamicUnionFormatter<T> seems applicable for not only Interface or Abstract Class but also ordinary Class.

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#91]
![image](https://user-images.githubusercontent.com/6511226/205611227-68c43193-6c70-4653-a73f-6b4925bc1383.png)

is the following possible?  I did so in my project, need official confirmation.

```
[MemoryPackable] public partial class  MyClass
[MemoryPackable] public partial class  MySubClass1: MyClass
[MemoryPackable] public partial class  MySubClass2: MyClass

MemoryPackFormatterProvider.Register(new DynamicUnionFormatter<MyClass>(
new []{
(0,typeof(MySubClass1),
(1,typeof(MySubClass2))
}));
```

Please confirm this and update doc.

and this feature is important for serialization/deserialization of Generaic Colleciton types, such as List<T>, where T is a non-abstract class, to be properly deserializaed to collection containing different subtypes.

e.g. if u want to deserliaze `List<MyClass>()`, which contains subtypes such as MySubClass1 and MySubClass2.

**Comment by xiaoyuvax** [comment]
It's useful 
1) when u don't have to register for the entire hierachial tree derived from an interface, but only to register for the branch derived from a specific class.  
2) when a class is neither derived from any interface nor abstract type.

Hope u keep this feature and write a remark about it.

**Comment by neuecc** [comment]
We initially had plans to implement it.
However, there are several edge cases and it will take time to implement a solution to them.
Therefore, we will not implement it for a while.
