### ISSUE TITLE
Code generator compile error CS0425 / Serialize() on MAUI(net7.0-windows***) target framework

### ISSUE THREAD

**Issue by espenrl** [Cysharp/MemoryPack#97]
I get an error with the example code.

```
[MemoryPackable]
public partial class Person
{
    public int Age { get; set; }
    public string Name { get; set; }
}
```

```
Person.MemoryPackFormatter.g.cs(55,24,55,33): error CS0425: The constraints for type parameter 'TBufferWriter' of method 'Person.Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter>, scoped ref Person?)' must match the constraints for type parameter 'TBufferWriter' of interface method 'IMemoryPackable<Person>.Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter>, scoped ref Person?)'. Consider using an explicit interface implementation instead.
```

```
[global::MemoryPack.Internal.Preserve]
    static void IMemoryPackable<Person>.Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, scoped ref Person? value) 
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(2, value.@Age);
        writer.WriteString(value.@Name);

    END:

        return;
    }
```

If I try to implement ` IMemoryPackable<Person>` directly `TBufferWriter` is constrained to `IBufferWriter<byte>` which doesn't happen in the autogenerated code.

```
public partial class Person : IMemoryPackable<Person>
{
    public int Age { get; set; }
    public string Name { get; set; }

    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref Person? value) where TBufferWriter : IBufferWriter<byte>
    {
        throw new NotImplementedException();
    }

    public static void Deserialize(ref MemoryPackReader reader, ref Person? value)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by neuecc** [comment]
which version(.NET / IDE / TargetFramework) do you use?

**Comment by espenrl** [comment]
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.5.0 Preview 1.0

**Comment by espenrl** [comment]
https://github.com/espenrl/issue-repro/tree/main/memorypack-cs0425

This is a `dotnet new maui` template showing the error. I tested that the error doesn't occur with `dotnet new console`.

**Comment by neuecc** [comment]
It seems bug of MAUI's compilation process.
For explicit implementations, constraint is inherited.
In fact, if you copy-paste the generated code, it will compile!
Yet, only in the case of Source Generator, I get a puzzling error.

The workaround is to create a net7 project where the generative types are placed and then referenced by the MAUI project.

**Comment by espenrl** [comment]
I know MAUI ties into MSBuild, but I can't see how it would affect the compiler. I'll look into it when I have time. Thanks for your feedback.

**Comment by neuecc** [comment]
only `<TargetFrameworks>net7.0-windows10.0.19041.0</TargetFrameworks>` fails.
I don't know the reason.

**Comment by espenrl** [comment]
It works with the latest MAUI tooling, both with Visual Studio and `dotnet build`. Closing the issue.

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.5.0 Preview 5.0

MAUI .NET7 SR3
