### ISSUE TITLE
Union with generic interface generates MEMPACK013

### ISSUE THREAD

**Issue by Wyzzcow** [Cysharp/MemoryPack#99]
Hi! Very nice looking library, however, the following is not working and I am not certain if this use-case should work. 
```
    [MemoryPackable]
    [MemoryPackUnion(0, typeof(FooClass))]
    [MemoryPackUnion(1, typeof(BarClass))]
    public partial interface IUnionSample<T>
    {
        public T Key { get; set; }
    }

    [MemoryPackable]
    public partial class FooClass : IUnionSample<string>
    {
        public int XYZ { get; set; }
        public string Key { get; set; }
    }

    [MemoryPackable]
    public partial class BarClass : IUnionSample<string>
    {
        public string? OPQ { get; set; }
        public string Key { get; set; }
    }
```
This generates
[MEMPACK013] The MemoryPackable object 'IUnionSample' union member 'FooClass' not implment union interface
[MEMPACK013] The MemoryPackable object 'IUnionSample' union member 'BarClass' not implment union interface

FYI, small typo in the error string `implment ` should be `implement`.

Thanks!

**Comment by neuecc** [comment]
For example, `IUnionSample<int>` could be serialized in FooClass, so
I think this is a case where it is not allowed.
Thanks for pointing out Typo, I will fix that.
